// osakenpiro DD (Design Dashboard) v3 — shared data
// Inherits from lp/data.js, adds `hh` (HumusHuman) section.
// Edit once, everything updates.

window.OSK_DATA = {
  hero: {
    name_ja: '長田 謙志郎',
    name_en: 'Kenshiro Osada',
    yomi: 'おさだ けんしろう',
    roles_en: ['ADHD Web Developer', 'Independent Philosopher'],
    roles_ja: ['フリー開発者', '独立研究者'],
    location: 'Tokyo, JP',
    handle: '@osakenpiro',
    tagline_ja: '全人類UX改善計画',
    tagline_en: 'the universal-UX-improvement plan',
    manifesto_ja: '宇宙の片隅で、ひとりで考えごとをしている夜',
    manifesto_en: 'a night spent thinking alone in a corner of the universe',
    orcid: '0009-0004-9167-3186',
  },

  // 9 papers. #9 is "preparing" — no DOI yet.
  // `tone` = post-it color (per-paper core color, 9 distinct hues).
  papers: [
    { n: 'I',    ja: '欲望の形態学',         en: 'Morphology of Desire',       short_ja: '欲望',     venue: 'Zenodo', doi: '10.5281/zenodo.19106655', year: 2025, core: true,
      tone: '#f4c95d', file: 'papers/paper-I-morphology-of-desire.html' },
    { n: 'II',   ja: 'アラインメントの公転', en: 'Circulation of Alignment',   short_ja: '公転',     venue: 'Zenodo', doi: '10.5281/zenodo.19106657', year: 2025,
      tone: '#a8c79b', file: 'papers/paper-II-circulation-of-alignment.html' },
    { n: 'III',  ja: '江湖原則',             en: 'Jianghu Principle',          short_ja: '江湖',     venue: 'Zenodo', doi: '10.5281/zenodo.19106661', year: 2025,
      tone: '#e89b7a', file: 'papers/paper-III-jianghu-principle.html' },
    { n: 'IV',   ja: '思考資本',             en: 'Thought-Capital',            short_ja: '資本',     venue: 'Zenodo', doi: '10.5281/zenodo.19106671', year: 2025,
      tone: '#c9a8e0', file: 'papers/paper-IV-thought-capital.html' },
    { n: 'V',    ja: 'アイデアの遺伝学',     en: 'Genetics of Ideas',          short_ja: '遺伝',     venue: 'Zenodo', doi: '10.5281/zenodo.19106673', year: 2025,
      tone: '#7fb8c4', file: 'papers/paper-V-genetics-of-ideas.html' },
    { n: 'VI',   ja: '心のグラデーション',   en: 'Gradient of Kokoro',         short_ja: '心',       venue: 'Zenodo', doi: '10.5281/zenodo.19106676', year: 2025,
      tone: '#ef9a9a', file: 'papers/paper-VI-gradient-of-kokoro.html' },
    { n: 'VII',  ja: '自在の引力',           en: 'Gravity of Jizai',           short_ja: '自在',     venue: 'Zenodo', doi: '10.5281/zenodo.19106695', year: 2025,
      tone: '#f0d36a', file: 'papers/paper-VII-gravity-of-jizai.html' },
    { n: 'VIII', ja: '三の基底状態',         en: 'Ground State of Three',      short_ja: '三',       venue: 'Zenodo', doi: '10.5281/zenodo.19106680', year: 2025,
      tone: '#b8d08a', file: 'papers/paper-VIII-ground-state-of-three.html' },
    { n: 'IX',   ja: '解読鍵',               en: 'Decryption Key',             short_ja: '解読',     venue: 'Zenodo', doi: null,                      year: null, pending: true,
      tone: '#d9d9d9', file: 'papers/paper-IX-decryption-key.html' },
  ],

  creative: [
    { kind: 'manga',   ja: 'PEACE PIECE',    en: 'PEACE PIECE',       meta: '連載 · manga',          detail: '戦争と静寂の短篇集',      url: 'https://rookie.shonenjump.com/series/zGZPbQ8SCbs' },
    { kind: 'novel',   ja: '星は知らない',   en: 'Hoshi wa Shiranai', meta: '8章 · SF長編',           detail: '超長期的孤独のSF',        url: 'https://kakuyomu.jp/works/16817330664193948573' },
    { kind: 'novel',   ja: '0.5の魔女',      en: '0.5 no Majo',       meta: '連載中 · カクヨム',      detail: '連続値で生きる魔女',      url: '#' },
    { kind: 'picture', ja: 'じこしょうかい', en: 'Jikoshoukai',       meta: '全17巻 · 85キャラ完結',  detail: '自己紹介という哲学行為', url: 'https://osakenpiro.github.io/jikoshoukai/' },
  ],

  // GEN:TOOLS:START — gen_dd.py (成果物DB=正本 / 手書き編集はDB側メモ・名前へ)
  tools: [
    { icon: "🎮", ja: "はざま / HAZAMA", en: "hazama", sub: "ファジー論理パズル＋【工房＝自由配線サンドボックス】 · 0.95", stack: "single html · game", url: "https://osakenpiro.github.io/hazama/", pillar: "G", hero: true },
    { icon: "🛠", ja: "社会考証ビジュアライザ（ひとRe:）", en: "shakai-vis", sub: "ひとRe:(人類消失SF)の社会全体考証ツール · 0.94", stack: "single html", url: "https://osakenpiro.github.io/shakai-vis/", pillar: "B", hero: true },
    { icon: "🎲", ja: "バク運スカウター — 運力計測器", en: "bakuun-scouter", sub: "運の計測と運の貯金 — 遊ばない日が運になる運力計測器 · 0.90", stack: "single html · game", url: "https://osakenpiro.github.io/bakuun-scouter/", pillar: "G", comic: "/works/images/motif/bakuun-scouter_sq.jpg", hero: true },
    { icon: "⚖", ja: "フリコ / FURIKO — 決断の振り子", en: "furiko", sub: "二択の迷いを0.0〜1.0の連続値にする決断の振り子 · 0.90", stack: "single html", url: "https://osakenpiro.github.io/furiko/", pillar: "T", hero: true },
    { icon: "🛠", ja: "三つ編み / Mitsuami", en: "mitsuami", sub: "名前を音韻×意味×構造の三層Floatで編む三重がけ命名ツール · 0.90", stack: "single html", url: "https://osakenpiro.github.io/mitsuami/", pillar: "T", hero: true },
    { icon: "⚔", ja: "僕のダンジョン", en: "dungeon", sub: "cosmos(僕の惑星)18ノード流用の単層fog-of-war探索マップ＝裏返しの惑星 · 0.90", stack: "single html", url: "https://osakenpiro.github.io/dungeon/", pillar: "T", hero: true },
    { icon: "🃏", ja: "帝国運用カードゲーム ECG", en: "ecg", sub: "74枚/op29種・単一HTML 154,014B(file://可)・vs CPU+2P・デッキビルダー・神話残篇4句… · 0.90", stack: "single html · game", url: "https://osakenpiro.github.io/ecg/", pillar: "G", comic: "/works/images/motif/ecg_sq.jpg", hero: true },
    { icon: "🚪", ja: "玄関 — 全部がぼく", en: "osakenpiro.github.io", sub: "DB=正本の自動生成玄関(gen_entrance v3) · 0.90", stack: "landing page", url: "https://osakenpiro.github.io/", hero: true },
    { icon: "🧩", ja: "部品工場 PARTS — コピペ部品ライブラリ", en: "parts", sub: "自己完結コピペ部品36点+ひとあかり素材棚24枚 · 0.90", stack: "single html", url: "https://osakenpiro.github.io/parts/", pillar: "R", comic: "/works/images/motif/parts_sq.jpg", hero: true },
    { icon: "🌌", ja: "僕の銀河系 Galaxy", en: "galaxy", sub: "Visionium全体構造をforce-directed graphで可視化(観測層L3b) · 0.87", stack: "single html", url: "https://osakenpiro.github.io/galaxy/", pillar: "R", comic: "/works/images/motif/galaxy_sq.jpg", hero: true },
    { icon: "🎮", ja: "0.5の魔女 / HALF-WITCH 魔法力配分パズル", en: "majo", sub: "保存された魔法力（Float予算）を呪文に配分するパズル · 0.85", stack: "single html · game", url: "https://osakenpiro.github.io/majo/", pillar: "G", hero: true },
    { icon: "🚪", ja: "あそびば / Boolean→Float Playground", en: "asobiba", sub: "Boolean→Floatを手で触れて遊ぶ７作の入口（遊び場ハブ） · 0.85", stack: "landing page", url: "https://osakenpiro.github.io/asobiba/", pillar: "G", hero: true },
    { icon: "🛠", ja: "あらいざらい (araizarai) — サブスク洗い出し＆解約ナビ", en: "araizarai", sub: "クレカ明細を貼る→契約中サブスクを自動検出→解約方法6分類＋難度Float(0..1)＋解約ページ入口URL · 0.85", stack: "single html", url: "https://osakenpiro.github.io/araizarai/", pillar: "T", hero: true },
    { icon: "🛠", ja: "うなり / UNARI", en: "unari", sub: "音のBoolean→Float · 0.85", stack: "single html", url: "https://osakenpiro.github.io/unari/", pillar: "R", hero: true },
    { icon: "🛠", ja: "かげん / KAGEN 所属度エクスプローラ", en: "kagen", sub: "ファジィ集合の所属度（grade of membership, Zadeh 1965）を手で動かす可視化ツール · 0.85", stack: "single html", url: "https://osakenpiro.github.io/kagen/", pillar: "T", hero: true },
    { icon: "📏", ja: "ものさし", en: "monosashi", sub: "白黒の決めつけを、Floatの目盛りと評価軸転換でほどくリフレーミング道具 · 0.85", stack: "single html", url: "https://osakenpiro.github.io/monosashi/", pillar: "T", hero: true },
    { icon: "🛠", ja: "ゆらぎ / YURAGI", en: "yuragi", sub: "p5.js生成アート（流れ場×粒子群） · 0.85", stack: "single html", url: "https://osakenpiro.github.io/yuragi/", pillar: "R", hero: true },
    { icon: "🎮", ja: "バク運スカウター / BAKUUN SCOUTER", en: "bakuun", sub: "運をFloat資源として扱うpress-your-luck · 0.85", stack: "single html · game", url: "https://osakenpiro.github.io/bakuun/", pillar: "G", hero: true },
    { icon: "☁", ja: "フワッカ FUWAKKA", en: "fuwakka", sub: "done/not-doneをやめるfuzzy todo · 0.85", stack: "single html", url: "https://osakenpiro.github.io/fuwakka/", pillar: "T", comic: "/works/images/motif/fuwakka_sq.jpg", hero: true },
    { icon: "🎚", ja: "何度メーター NANDO-METER", en: "nandometer", sub: "迷いの要素を重みづけして確信度を0〜100%(Float)で測る · 0.85", stack: "single html", url: "https://osakenpiro.github.io/nandometer/", pillar: "T", comic: "/works/images/motif/nandometer_sq.jpg", hero: true },
    { icon: "🐢", ja: "怠け通し NAMAKE-DOOSHI", en: "namakedooshi", sub: "サボっても崩れない段階ストリーク習慣トラッカー · 0.85", stack: "single html", url: "https://osakenpiro.github.io/namakedooshi/", pillar: "T", comic: "/works/images/motif/namakedooshi_sq.jpg", hero: true },
    { icon: "📐", ja: "文体測り — Bun-tai Hakari", en: "buntai-hakari", sub: "原稿の読点率(主ダイヤル=、÷地の文字数・基準3.5%=IMASICA文体ガイドv0作者承認)・65字超・過剰読点(主語… · 0.85", stack: "single html", url: "https://osakenpiro.github.io/buntai-hakari/", pillar: "T", hero: true },
    { icon: "🌊", ja: "深海テスト — Shinkai Test", en: "shinkai", sub: "9問の潜水型6軸診断(PHI/CRE/TEC/OUT/VIT/EXP) · 0.85", stack: "single html", url: "https://osakenpiro.github.io/shinkai/", pillar: "T", comic: "/works/images/motif/shinkai_sq.jpg", hero: true },
    { icon: "🧱", ja: "IMASICA — 想像を立体で書く", en: "imasica", sub: "ブロック建築の立体設計図 · 0.80", stack: "single html", url: "https://osakenpiro.github.io/imasica/", pillar: "T", hero: true },
    { icon: "🛠", ja: "kokoro-guruguru（トマリぐるぐる / 魚乃ココロ受肉）", en: "guruguru", sub: "魚乃ココロ(IMASICA A型)の受肉ブラウザアバター · 0.80", stack: "single html", url: "https://osakenpiro.github.io/kokoro-guruguru/guruguru.html", pillar: "T", hero: true },
    { icon: "👣", ja: "あしあとマップ — Ashiato Map", en: "ashiato", sub: "地面に残すサイン · 0.80", stack: "single html", url: "https://osakenpiro.github.io/ashiato/", pillar: "T", hero: true },
    { icon: "🎮", ja: "あわい / AWAI", en: "awai", sub: "Boolean→Float を“遊べる機構”に · 0.80", stack: "single html · game", url: "https://osakenpiro.github.io/awai/", pillar: "G", hero: true },
    { icon: "🚪", ja: "おすそわけ / OSUSOWAKE", en: "osusowake", sub: "Boolean→Float三部作(あわい/なおしかた/あんばい)の届け先LP · 0.80", stack: "landing page", url: "https://osakenpiro.github.io/osusowake/", pillar: "P", hero: true },
    { icon: "🛠", ja: "げんてん / GENTEN", en: "genten", sub: "Boolean→Floatの原典オーパーツ · 0.80", stack: "single html", url: "https://osakenpiro.github.io/genten/", pillar: "O", hero: true },
    { icon: "🛠", ja: "なおしかた / NAOSHIKATA", en: "naoshikata", sub: "Re:DeSign Boolean→Float パターン図鑑 · 0.80", stack: "single html", url: "https://osakenpiro.github.io/naoshikata/", pillar: "R", hero: true },
    { icon: "🎮", ja: "ドラコロバトル / DRACORO ARENA", en: "dracoro", sub: "skill-vs-luckデュエル · 0.80", stack: "single html · game", url: "https://osakenpiro.github.io/dracoro/", pillar: "G", hero: true },
    { icon: "🪟", ja: "ワクワク — Wakuwaku Skeleton", en: "wakuwaku", sub: "白紙恐怖を消す長編スケルトン · 0.80", stack: "single html", url: "https://osakenpiro.github.io/wakuwaku/", pillar: "T", hero: true },
    { icon: "📇", ja: "人類の素材図鑑 — 目次（素材ライン5系統の索引）", en: "sozai-zukan-mokuji", sub: "素材を扱う出荷物5系統（3D教科書3本／素材図鑑11章／絵本17冊／社会のながれ／地球でえた）を標本と番号で束ねた索引 · 0.80", stack: "—", url: "https://osakenpiro.github.io/sozai-zukan-mokuji/", pillar: "T", hero: true },
    { icon: "🔁", ja: "Queue Dashboard", en: "queue-dashboard", sub: "磨きどころレーダー(放置日数×完成度Float) · 0.75", stack: "single html", url: "https://osakenpiro.github.io/re-design/queue-dashboard.html", pillar: "R", hero: true },
    { icon: "🪲", ja: "Fable記 図鑑（思想の博物誌）", en: "fable-ki", sub: "思想の博物誌 · 0.72", stack: "single html", url: "https://osakenpiro.github.io/fable-ki/", pillar: "B", hero: true },
    { icon: "🛠", ja: "FABULA — システムの分類学", en: "fabula", sub: "システムの分類学=系統樹ツール · 0.70", stack: "single html", url: "https://osakenpiro.github.io/fabula/", pillar: "T", hero: true },
    { icon: "📖", ja: "WORKS — ぜんぶのとりせつ（トリセツ工場）", en: "works", sub: "全成果物のとりせつ（紹介ページ）一括生成層（大行軍v2 Lane ι SES-428） · 0.70", stack: "landing page", url: "https://osakenpiro.github.io/works/", pillar: "R", hero: true },
    { icon: "⚔", ja: "ステータス — RPG STATUS（経験値の現在地）", en: "status", sub: "RPG Status DB→miha latest.json集計をLv/XP/系統別バーで表示 · 0.70", stack: "single html", url: "https://osakenpiro.github.io/status/", hero: true },
    { icon: "🌍", ja: "HELLO WAR(L)D — 地図とりあい観察庭", en: "hello-warld", sub: "P0ソロ観察庭（大行軍v2 Laneδ、SES-404土地神分身 2026-06-06、commit c73a5815） · 0.60", stack: "single html · game", url: "https://osakenpiro.github.io/hello-warld/", pillar: "G", hero: true },
    { icon: "💤", ja: "夢見る少女は眠れない", en: "yumemi-shoujo", sub: "起こさないで遊ぶ二重放置ゲー — 少女が自然に目覚めるのを待つと夢が聞ける · 0.55", stack: "single html · game", url: "https://osakenpiro.github.io/yumemi-shoujo/", pillar: "G", comic: "/works/images/motif/yumemi-shoujo_sq.jpg", hero: true },
    { icon: "🫁", ja: "Breathe", en: "breathe", sub: "4-7-8/Box/Calm 呼吸法ガイド", stack: "single html", url: "https://osakenpiro.github.io/breathe/", pillar: "T", comic: "/works/images/motif/breathe_sq.jpg", hero: true },
    { icon: "🎵", ja: "HIBIKI", en: "hibiki", sub: "4コードアルペジオメーカー", stack: "single html", url: "https://osakenpiro.github.io/hibiki/", pillar: "T", hero: true },
    { icon: "💡", ja: "HIRAMEKI", en: "hirameki", sub: "世界を良くするアイデアをカード化してXに蒔く", stack: "single html", url: "https://osakenpiro.github.io/hirameki/", pillar: "T", comic: "/works/images/motif/hirameki_sq.jpg", hero: true },
    { icon: "🪞", ja: "KAGAMI（鏡）", en: "kagami", sub: "毎日ひとつの問い→洞察→行動をXに記録する日記ツール", stack: "single html", url: "https://osakenpiro.github.io/kagami/", pillar: "T", comic: "/works/images/motif/kagami_sq.jpg", hero: true },
    { icon: "🗾", ja: "KON-NICHI-WAR(L)D", en: "konnichiwarld", sub: "美しい日本語を1枚ずつ学ぶカード", stack: "single html", url: "https://osakenpiro.github.io/konnichiwarld/", pillar: "T", hero: true },
    { icon: "📊", ja: "MIERU（見える）", en: "MIERU", sub: "CSVをアップロードして可視化するツール", stack: "single html", url: "https://osakenpiro.github.io/MIERU/", pillar: "T", comic: "/works/images/motif/mieru_sq.jpg", hero: true },
    { icon: "◉", ja: "SATORI", en: "SATORI", sub: "開眼系AI賢人", stack: "Claude API · CF Worker", url: "https://osakenpiro.github.io/satori/", pillar: "T", comic: "/works/images/motif/satori_sq.jpg", hero: true },
    { icon: "🧙", ja: "VR Akinator", en: "vr-akinator", sub: "分類法のメタ分類(双子構造の片割れ)", stack: "single html", url: "https://osakenpiro.github.io/vr-akinator/", pillar: "G", hero: true },
    { icon: "📋", ja: "Web制作ヒアリングシート", en: "hearing-sheet", sub: "LP/Web制作案件の初回ヒアリングフォーム", stack: "single html", url: "https://osakenpiro.github.io/hearing-sheet/", pillar: "P", hero: true },
    { icon: "🔆", ja: "big-light（ビッグライト）", en: "big-light", sub: "ビッグライトモード共通規格(CSS/JSライブラリ、CDN配布、MIT)", stack: "—", url: "https://osakenpiro.github.io/big-light/", pillar: "R", hero: true },
    { icon: "📇", ja: "contact（名刺）", en: "contact", sub: "名刺 FILE 003", stack: "landing page", url: "https://osakenpiro.github.io/contact/", hero: true },
    { icon: "🌏", ja: "cosmos（軌道）", en: "Boku no Wakusei", sub: "軌道 FILE 004", stack: "single html · canvas", url: "https://osakenpiro.github.io/cosmos/", pillar: "T", hero: true },
    { icon: "📜", ja: "godwiki（神話DB）", en: "godwiki", sub: "ギリシャ・北欧・日本の神話エピソードDB(24件)", stack: "—", url: "https://osakenpiro.github.io/godwiki/", pillar: "B", hero: true },
    { icon: "🛠", ja: "⌨ Shortcuts & Tools", en: "shortcuts", sub: "PowerToys/Windows/Chrome/Clip Studio/ComfyUI/Tartarus V2/Str…", stack: "single html", url: "https://osakenpiro.github.io/shortcuts/", pillar: "T", hero: true },
    { icon: "🔘", ja: "あいまい / AIMAI", en: "aimai", sub: "「はい・いいえ」をやめるボタン", stack: "single html", url: "https://osakenpiro.github.io/aimai/", pillar: "T", hero: true },
    { icon: "💡", ja: "あったらいいな図鑑", en: "attara-iina", sub: "みんなの『あんなこといいな』を投稿で集める", stack: "landing page", url: "https://osakenpiro.github.io/attara-iina/", pillar: "P", hero: true },
    { icon: "🍵", ja: "あまっちゃ／にがっちゃ", en: "amaccha-nigaccha", sub: "抹茶の甘さを0.0〜1.0で選ぶ Boolean→Float飲料UX試作", stack: "landing page", url: "https://osakenpiro.github.io/amaccha-nigaccha/", pillar: "T", hero: true },
    { icon: "🧬", ja: "じこしょうかいシリーズ（絵本全17巻）", en: "Jikoshoukai Portal", sub: "絵本シリーズ全１７巻ポータル(85キャラ)", stack: "single html", url: "https://osakenpiro.github.io/jikoshoukai/", pillar: "B", hero: true },
    { icon: "📚", ja: "たなずかん", en: "tana-zukan", sub: "tier shelf dictionary", stack: "single html", url: "https://osakenpiro.github.io/tana-zukan/", pillar: "T", hero: true },
    { icon: "🎮", ja: "ぼうけんのしょ", en: "boukennosho", sub: "積みゲーを倒すRPG風の積みゲー管理ツール", stack: "single html", url: "https://osakenpiro.github.io/boukennosho/", pillar: "T", comic: "/works/images/motif/boukennosho_sq.jpg", hero: true },
    { icon: "💰", ja: "わたしのお財布", en: "Watashi Wallet", sub: "日本人の自由度マップ", stack: "D3.js · real data", url: "https://osakenpiro.github.io/watashi-wallet/", pillar: "T", comic: "/works/images/motif/watashi-wallet_sq.jpg", hero: true },
    { icon: "🐸", ja: "わっかずかん", en: "Wakka-zukan", sub: "同心円でカテゴリを並べる視覚分類器(#01分類わっか)", stack: "localStorage · SVG", url: "https://osakenpiro.github.io/wakkazukan/", pillar: "T", comic: "/works/images/motif/wakkazukan_sq.jpg", hero: true },
    { icon: "🌀", ja: "バネットマップ / Banet Map", en: "banet-map", sub: "力学的関係ビジュアライザ", stack: "single html", url: "https://osakenpiro.github.io/banet-map/", pillar: "T", hero: true },
    { icon: "📕", ja: "パンダと哲学とAI（KDP）", en: "B0GT4HJBF4", sub: "KDP書籍", stack: "—", url: "https://www.amazon.co.jp/dp/B0GT4HJBF4", pillar: "P", hero: true },
    { icon: "🎨", ja: "ポートフォリオデモ（制作デモ）", en: "portfolio-demos", sub: "制作デモ(ベーカリーLPこむぎ日和/SaaS LP FlowTask)", stack: "landing page", url: "https://osakenpiro.github.io/portfolio-demos/", pillar: "P", hero: true },
    { icon: "✴", ja: "メの島 / ME-NO-SHIMA", en: "me-no-shima", sub: "ぽこあポケモン由来ファンメイド島構想・建築設計書シリーズ（全13施設+全体図+別館、画像14枚）", stack: "—", url: "https://osakenpiro.github.io/me-no-shima/", hero: true },
    { icon: "📗", ja: "人類の素材図鑑（KDP）", en: "B0GX2X9YF3", sub: "KDP書籍", stack: "—", url: "https://www.amazon.co.jp/dp/B0GX2X9YF3", pillar: "P", hero: true },
    { icon: "⚔", ja: "六剋（りくこく）", en: "rikkoku", sub: "斬・刺・打・固・軟・翻の六属性が剋しあう Boolean→Float RPG", stack: "single html · game", url: "https://osakenpiro.github.io/rikkoku/", pillar: "G", comic: "/works/images/motif/rikkoku_sq.jpg", hero: true },
    { icon: "🗂", ja: "役割分化地図", en: "topology", sub: "誰が何を担当するか、Visioniumを7層構造で解剖", stack: "single html", url: "https://osakenpiro.github.io/ecosystem/topology.html", pillar: "R", hero: true },
    { icon: "🗾", ja: "日本のお財布", en: "Japan Wallet Map", sub: "人口と権力の1400年、東京一極集中をバブルで可視化", stack: "D3.js · TopoJSON", url: "https://osakenpiro.github.io/japan-wallet-map/", pillar: "T", hero: true },
    { icon: "🏯", ja: "日本可視化列島", en: "japan-visualization", sub: "人口動態・家計・地震の日本可視化ツール群ハブ", stack: "landing page", url: "https://osakenpiro.github.io/japan-visualization/", pillar: "T", hero: true },
    { icon: "🌏", ja: "日本地震マップ", en: "japan-earthquake-map", sub: "1850-2060年の震災を三重同心円で可視化", stack: "single html", url: "https://osakenpiro.github.io/japan-earthquake-map/", pillar: "T", hero: true },
    { icon: "🌙", ja: "月 — osakenpiro tools", en: "moon", sub: "osakenpiro全ツール一覧ポータル", stack: "landing page", url: "https://osakenpiro.github.io/moon/", pillar: "T", hero: true },
    { icon: "🔥", ja: "炎上！SNS", en: "enjou-sns", sub: "炎上シミュレーター v6", stack: "single html · game", url: "https://osakenpiro.github.io/enjou-sns/", pillar: "G", comic: "/works/images/motif/enjou-sns_sq.jpg", hero: true },
    { icon: "🧩", ja: "生態系チェッカー", en: "ecosystem-checker", sub: "持っている道具とプランから到達度と追加機能を判定", stack: "single html", url: "https://osakenpiro.github.io/ecosystem-checker/", pillar: "T", hero: true },
    { icon: "🌐", ja: "生態系相関総観", en: "ecosystem", sub: "データがどう巡るか、軽アニメで見る生態系フロー", stack: "single html", url: "https://osakenpiro.github.io/ecosystem/", pillar: "R", hero: true },
    { icon: "📌", ja: "画鋲（pin-wall）", en: "Pin-Wall (gabyo)", sub: "生成画像を貼る場", stack: "single html · CF Worker", url: "https://osakenpiro.github.io/pin-wall/", pillar: "T", hero: true },
    { icon: "🔢", ja: "百ますグリッド", en: "hyakumasu", sub: "百ますグリッド hyakumasu", stack: "single html", url: "https://osakenpiro.github.io/hyakumasu/", pillar: "G", hero: true },
    { icon: "🌊", ja: "社会のながれ — よこから見るか、たてから見るか", en: "nagare", sub: "同じ社会を2方向から", stack: "single html", url: "https://osakenpiro.github.io/nagare/", pillar: "T", hero: true },
    { icon: "🦊", ja: "立体図鑑 zukan3d", en: "zukan3d", sub: "駒・素材を3D/ARで観る図鑑", stack: "GLB · manifest", url: "https://osakenpiro.github.io/zukan3d/", pillar: "T", comic: "/works/images/motif/zukan3d_sq.jpg", hero: true },
    { icon: "🧪", ja: "素材図鑑（ツール版）", en: "Materials of Civilization", sub: "文明を素材の系譜として並べる(#05)", stack: "D3.js · single html", url: "https://osakenpiro.github.io/materials-of-civilization/", pillar: "T", hero: true },
    { icon: "🛡", ja: "護錆（人類の素材図鑑 3D教科書 No.002）", en: "gosei", sub: "副題「錆びない金属ほど、よく錆びる」", stack: "GLB · manifest", url: "https://osakenpiro.github.io/gosei/", pillar: "T", hero: true },
    { icon: "🦴", ja: "還蹄（人類の素材図鑑 3D教科書・生物編）", en: "kantei", sub: "副題「見た目を捨てても、踝の骨が血をおぼえている」", stack: "GLB · manifest", url: "https://osakenpiro.github.io/kantei/", pillar: "T", hero: true },
    { icon: "🪨", ja: "黒曜片（人類の素材図鑑 3D教科書 No.001）", en: "kokuyouhen", sub: "黒曜石＝鉱物の定義を満たさない「ガラス」", stack: "GLB · manifest", url: "https://osakenpiro.github.io/kokuyouhen/", pillar: "T", hero: true },
    { icon: "🧠", ja: "概念辞典 — 法則・効果・原理・剃刀", en: "gainen", sub: "法則・効果・原理・剃刀を一行定義+創作フックで蓄積(60件) · 0.85", stack: "—", url: "https://osakenpiro.github.io/gainen/" },
    { icon: "🏮", ja: "格言辞典 — 創作参照層", en: "kakugen", sub: "創作参照3DBの1つ · 0.80", stack: "—", url: "https://osakenpiro.github.io/kakugen/" },
    { icon: "🎨", ja: "秀逸表現辞典 — コピペ・ミーム・名セリフ・帯・書き出し", en: "hyogen", sub: "優れた表現を技法分析+短い引用(15語未満)+出典で蓄積(21件) · 0.80", stack: "—", url: "https://osakenpiro.github.io/hyogen/" },
    { icon: "🔌", ja: "Discord配管マップ (disco-map)", en: "disco-map", sub: "disco-overhaul Phase D · 0.70", stack: "single html", url: "https://osakenpiro.github.io/disco-map/" },
    { icon: "💰", ja: "Finance", en: "finance-dashboard", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/finance-dashboard/" },
    { icon: "🗾", ja: "Japan × ASEAN 関係マップ", en: "japan-asean-map", sub: "日本と東南アジア10カ国の関係性を貿易・安保・経済協力の3ビューで可視化", stack: "single html", url: "https://osakenpiro.github.io/japan-asean-map/" },
    { icon: "⚔", ja: "RPG Status", en: "rpg-status", sub: "Lv.14 | PHI 73 CRE 58 TEC 70 OUT 36 VIT 44 EXP 69", stack: "single html · game", url: "https://osakenpiro.github.io/rpg-status/", pillar: "G" },
    { icon: "📅", ja: "Shukan — Float Habit Tracker", en: "shukan", sub: "習慣を「やった/やらない」の二択でなく 0 / 0.25 / 0.5 / 0.75 / 1.0 の Float で記録す…", stack: "single html", url: "https://osakenpiro.github.io/shukan/" },
    { icon: "🃏", ja: "pokechan-cheatsheets | Pokemon Champions battle cheatsheets - 1041流 strategic team guides", en: "pokechan-cheatsheets", sub: "Pokemon Champions battle cheatsheets - 1041流 strategic team …", stack: "single html", url: "https://osakenpiro.github.io/pokechan-cheatsheets/" },
    { icon: "🛠", ja: "⏳ ゆとり / YUTORI — 間に合う・間に合わないを、やめる。", en: "yutori", sub: "「間に合う/間に合わない」を0か1かでやめる", stack: "single html", url: "https://osakenpiro.github.io/yutori/" },
    { icon: "🌗", ja: "あわい — Float field / 二値が溶ける庭", en: "lane1-awai", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/lane1-awai/" },
    { icon: "🏘", ja: "あわいむら — 二値では治まらない村", en: "awaimura", sub: "はい／いいえ、ではない", stack: "single html · game", url: "https://osakenpiro.github.io/awaimura/", pillar: "G" },
    { icon: "🌳", ja: "いのちの樹 · わっかずかん — 3D生物分類", en: "wakka-tree", sub: "最終普遍共通祖先LUCAから全生物へ", stack: "GLB · manifest", url: "https://osakenpiro.github.io/wakka-tree/", pillar: "T" },
    { icon: "🏠", ja: "おうちの天井 — はじめての家えらびに、明かりを", en: "ouchi-no-tenjo", sub: "家を買おうか迷っている2人へ", stack: "single html", url: "https://osakenpiro.github.io/ouchi-no-tenjo/" },
    { icon: "🏡", ja: "ずしのいえ", en: "zushinoie", sub: "「海の家」をもじって、ずしのいえ", stack: "single html", url: "https://osakenpiro.github.io/zushinoie/" },
    { icon: "⚗", ja: "はかりごと — Float Scales", en: "hakarigoto", sub: "「AかBか」で悩む判断を、複数の評価軸で 0.0–1.0 のスライダーに開き、重み付き加重平均で「今の自分の Float…", stack: "single html", url: "https://osakenpiro.github.io/hakarigoto/" },
    { icon: "🔺", ja: "みつかさ — 三重がけ命名ヘルパー", en: "mitsukasa", sub: "タイトルや名前を 音韻 × 意味 × 構造 の3層で同時に機能させる、三重がけ命名法のワークショップ", stack: "single html", url: "https://osakenpiro.github.io/mitsukasa/" },
    { icon: "🌫", ja: "もやもやメーター — 白黒つけない意思決定ツール", en: "moyamoya", sub: "二択・多択のもやもやを、スライダーでFloat（0.0〜1.0）にほぐす意思決定ツール", stack: "single html", url: "https://osakenpiro.github.io/moyamoya/" },
    { icon: "〰", ja: "ゆらぎ秤 — Boolean→Float 決定の秤", en: "yuragi-bakari", sub: "YesでもNoでもなく、0.5の重さを量る", stack: "single html", url: "https://osakenpiro.github.io/yuragi-bakari/" },
    { icon: "🔁", ja: "わのり — 使っても、減らない", en: "wanori", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/wanori/" },
    { icon: "🎲", ja: "オーパーツ・オッズ / OOPArts Odds — 別種度を賭ける", en: "oopaats-odds", sub: "ゲーム", stack: "single html · game", url: "https://osakenpiro.github.io/oopaats-odds/", pillar: "G" },
    { icon: "🧍", ja: "カタ — osakenpiroの地金", en: "kata", sub: "osakenpiroデザインシステムの実物", stack: "single html", url: "https://osakenpiro.github.io/kata/" },
    { icon: "🌗", ja: "キワ — 際に寄せる", en: "kiwa", sub: "当たり/外れじゃない", stack: "single html", url: "https://osakenpiro.github.io/kiwa/" },
    { icon: "🐟", ja: "サーモンラン 金バッジ遡上マップ", en: "salmonrun", sub: "スプラトゥーン3サーモンランで金バッジ（でんせつ999）に到達するための一枚もの", stack: "single html", url: "https://osakenpiro.github.io/salmonrun/" },
    { icon: "🎚", ja: "シボリ — 文章を締める", en: "shibori", sub: "読点・冗長・長文を可視化して文章を絞る", stack: "single html", url: "https://osakenpiro.github.io/shibori/" },
    { icon: "🧱", ja: "ツチカ — 腐葉土コンポスト", en: "tsuchika", sub: "文脈を地層に堆積させる", stack: "single html", url: "https://osakenpiro.github.io/tsuchika/" },
    { icon: "🌊", ja: "ナギ — 息をととのえる", en: "nagi", sub: "息を連続のかたちで", stack: "single html", url: "https://osakenpiro.github.io/nagi/" },
    { icon: "🤍", ja: "ハク — 連続値シーケンサ", en: "haku", sub: "オン/オフじゃない", stack: "single html", url: "https://osakenpiro.github.io/haku/" },
    { icon: "📐", ja: "ブループリント標準 v0.1 — Ap→Bp", en: "blueprint-standard", sub: "アプリ（Ap）の後継としてのブループリント（Bp）", stack: "single html", url: "https://osakenpiro.github.io/blueprint-standard/" },
    { icon: "👁", ja: "ミエ — 三重がけ命名盤", en: "mie", sub: "名前を 音韻×意味×構造 の3層で測る", stack: "single html", url: "https://osakenpiro.github.io/mie/" },
    { icon: "🎴", ja: "三重取りいろは ― osakenpiro 作歌支援", en: "sanju-iroha", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/sanju-iroha/" },
    { icon: "👤", ja: "人間図鑑 — 観察蒐集帖", en: "ningen-zukan", sub: "ふとした時に、人間性が垣間見える", stack: "single html", url: "https://osakenpiro.github.io/ningen-zukan/" },
    { icon: "💪", ja: "体でえた — 筋群ホログラム", en: "karada-de-eta", sub: "本物の解剖メッシュ467構造を青ホログラムで発光させ、トレーニング種目ごとに効く筋群をFloat濃淡で可視化する", stack: "single html", url: "https://osakenpiro.github.io/karada-de-eta/" },
    { icon: "🌌", ja: "僕の銀河系 — 客観レイヤ / embedding実測マップ", en: "galaxy-drift", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/galaxy-drift/" },
    { icon: "⚖", ja: "全世界ダッシュボード — 裁定者は可視化される", en: "saiteisha", sub: "政治経済の裁定者を、隠れた権威から「みんなが見て回せる可視化ダッシュボード」へ", stack: "single html", url: "https://osakenpiro.github.io/saiteisha/" },
    { icon: "🧾", ja: "全部がぼく — 棚卸し地図 (ReDes v0)", en: "tanaoroshi", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/tanaoroshi/" },
    { icon: "🕯", ja: "半灯宇宙 — Lane① / osakenpiro", en: "lane1", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/lane1/" },
    { icon: "🎮", ja: "半灯守り — 丸めない夜のゲーム", en: "lane1-game", sub: "ゲーム", stack: "single html · game", url: "https://osakenpiro.github.io/lane1-game/", pillar: "G" },
    { icon: "🕯", ja: "半灯（はんとう）", en: "lane1-hantou", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/lane1-hantou/" },
    { icon: "🌐", ja: "地球でえた — データで見る地球儀", en: "chikyu-de-eta", sub: "線だけで描かれた、裏側が透ける地球儀", stack: "single html", url: "https://osakenpiro.github.io/chikyu-de-eta/" },
    { icon: "📊", ja: "報告書半自動化プロジェクト — 設計ページ", en: "report-auto-f92469", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/report-auto-f92469/" },
    { icon: "🗓", ja: "楕円の暦 — 年を一枚で置く", en: "koyomi", sub: "楕円の暦 / KAN-REKI — 1年を一枚の楕円に置くライフログカレンダー", stack: "single html", url: "https://osakenpiro.github.io/koyomi/" },
    { icon: "🧰", ja: "毎日道具 — Daily Float計器", en: "dougu", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/dougu/" },
    { icon: "🌡", ja: "決定温度アニーラー", en: "ondo", sub: "選択肢を温度 τ の softmax で Float 確率に変換し、探索→収束の焼きなましで Boolean な決定に至…", stack: "single html", url: "https://osakenpiro.github.io/ondo/" },
    { icon: "🌙", ja: "深夜創作工房 — Lane⓪ / 全人類UX改善", en: "atelier", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/atelier/" },
    { icon: "🔥", ja: "焚べ（くべ） — 熱があるうちに、冷めたものは土になる", en: "kube", sub: "熱量Floatを機構そのものに据えた一夜のローグライト", stack: "single html · game", url: "https://osakenpiro.github.io/kube/", pillar: "G" },
    { icon: "📄", ja: "特定商取引法に基づく表記", en: "tokushoho", sub: "特定商取引法に基づく表記 - osakenpiro（長田謙志郎）", stack: "—", url: "https://osakenpiro.github.io/tokushoho/" },
    { icon: "🎮", ja: "画面録（がめんろく） — スクリーンタイムRPG", en: "screen-time-rpg", sub: "スクリーンタイムを罪悪感じゃなく『鍛えているステータス』として読む", stack: "single html", url: "https://osakenpiro.github.io/screen-time-rpg/" },
    { icon: "⛰", ja: "磐境村 — 深度フィールド v1（真層）", en: "iwasaka", sub: "灯籠ひとつの光", stack: "single html", url: "https://osakenpiro.github.io/iwasaka/" },
    { icon: "🗺", ja: "統合凡例マップ — Boolean→Float 一望", en: "hanrei", sub: "HTMLツール", stack: "single html", url: "https://osakenpiro.github.io/hanrei/" },
    { icon: "🛠", ja: "耳コピ→TAB 自動採譜 v0.5 — mimicopy-tab", en: "mimicopy-tab", sub: "音声ファイルをブラウザ内でMIDI化し、運指最適化でギター/ベース/ウクレレのTAB譜に自動採譜", stack: "single html", url: "https://osakenpiro.github.io/mimicopy-tab/" },
    { icon: "🍂", ja: "腐土帖 — Fudo-cho", en: "fudocho", sub: "削除しない記憶", stack: "single html", url: "https://osakenpiro.github.io/fudocho/" },
    { icon: "🎬", ja: "銀幕亭 — 時めぐり", en: "ginmakutei", sub: "映画がむかし、落語だったら", stack: "single html", url: "https://osakenpiro.github.io/ginmakutei/" },
    { icon: "🎫", ja: "願い片道きっぷ", en: "negai-kippu", sub: "夜空を走る列車から、届かないかもしれない想いを送る", stack: "single html", url: "https://osakenpiro.github.io/negai-kippu/" },
    { icon: "☁", ja: "天人𦻙記", en: "Tenjin-ki", sub: "準備中", stack: "—", url: "#", pending: true },
  ],
  // GEN:TOOLS:END

  // HumusHuman — GUBr (game-character-select) section.
  // 6 立ち絵 slots. Images land later; for now, layout-only.
  // `ptds: true` = 秘書子 (gets physical-twin treatment: task tray + binder cabinet).
  hh: [
    { id: 'fire',   kind: 'SATORI', ja: '炎の賢者',      en: 'Sage of Fire',    element: '炎', tone: '#e89b7a' },
    { id: 'water',  kind: 'SATORI', ja: '水の賢者',      en: 'Sage of Water',   element: '水', tone: '#7fb8c4' },
    { id: 'wind',   kind: 'SATORI', ja: '風の賢者',      en: 'Sage of Wind',    element: '風', tone: '#a8c79b' },
    { id: 'earth',  kind: 'SATORI', ja: '土の賢者',      en: 'Sage of Earth',   element: '土', tone: '#c9a58a' },
    { id: 'moppoi', kind: 'PROXY',  ja: 'もっぽい/だらりん', en: 'Moppoi / Dararin', element: 'だらり', tone: '#d9d6cc' },
    { id: 'hishoco',kind: 'ASSIST', ja: '秘書子',        en: 'HishoCo',         element: '事務', tone: '#f4c95d', ptds: true },
  ],

  socials: [
    { k: 'X',        handle: '@osakenpiro',   url: 'https://x.com/osakenpiro',                 glyph: '𝕏', avatar: 'assets/sns-01-x-avatar.png', bg: 'assets/sns-01-x-bg.png' },
    { k: 'TikTok',   handle: '@panio54',    url: 'https://www.tiktok.com/@panio54',        glyph: '◈', avatar: 'assets/sns-02-tiktok-avatar.png', bg: 'assets/sns-02-tiktok-bg.png' },
    { k: 'pixiv',    handle: '@kenpiro7',   url: 'https://www.pixiv.net/users/11085694',   glyph: 'P', avatar: 'assets/sns-03-pixiv-avatar.png', bg: 'assets/sns-03-pixiv-bg.png' },
    { k: 'Kakuyomu', handle: '@osakenpiro', url: 'https://kakuyomu.jp/users/osakenpiro',   glyph: '書', avatar: 'assets/sns-04-kakuyomu-avatar.png', bg: 'assets/sns-04-kakuyomu-bg.png' },
    { k: 'note',     handle: '@osakenpiro', url: 'https://note.com/osakenpiro',            glyph: 'n', avatar: 'assets/sns-05-note-avatar.png', bg: 'assets/sns-05-note-bg.png' },
    { k: 'GitHub',   handle: 'osakenpiro',  url: 'https://github.com/osakenpiro',          glyph: '◉', avatar: 'assets/sns-06-github-avatar.png', bg: 'assets/sns-06-github-bg.png' },
  ],

  // GEN:DDTL:START — gen_dd.py 年表(台帳に載った日ベース・誕生日列なき正直設計)
  timeline: [
    { d: "2026-05-31", n: 46, label: "台帳創世 — 一斉登録", items: [] },
    { d: "2026-06-01", n: 1, items: [{ ja: "Discord配管マップ (disco-map)", url: "https://osakenpiro.github.io/disco-map/" }] },
    { d: "2026-06-02", n: 1, items: [{ ja: "メの島 / ME-NO-SHIMA", url: "https://osakenpiro.github.io/me-no-shima/" }] },
    { d: "2026-06-03", n: 4, items: [{ ja: "格言辞典 — 創作参照層", url: "https://osakenpiro.github.io/kakugen/" }, { ja: "概念辞典 — 法則・効果・原理・剃刀", url: "https://osakenpiro.github.io/gainen/" }, { ja: "秀逸表現辞典 — コピペ・ミーム・名セリフ・帯・書き出し", url: "https://osakenpiro.github.io/hyogen/" }, { ja: "画像正本ストア（Google Drive / Visionium/images）", url: null }] },
    { d: "2026-06-04", n: 1, items: [{ ja: "A＼mI／DA＼（ア・ミ・ダ）", url: "https://kakuyomu.jp/works/2912051601256382667" }] },
    { d: "2026-06-06", n: 8, items: [{ ja: "HELLO WAR(L)D — 地図とりあい観察庭", url: "https://osakenpiro.github.io/hello-warld/" }, { ja: "x-post スキル（X投稿 Web Intent方式）", url: "https://github.com/osakenpiro/claude-shared/tree/main/skills/x-post" }, { ja: "WORKS — ぜんぶのとりせつ（トリセツ工場）", url: "https://osakenpiro.github.io/works/" }, { ja: "あしあとマップ — Ashiato Map", url: "https://osakenpiro.github.io/ashiato/" }, { ja: "深海テスト — Shinkai Test", url: "https://osakenpiro.github.io/shinkai/" }, { ja: "夢見る少女は眠れない", url: "https://osakenpiro.github.io/yumemi-shoujo/" }, { ja: "部品工場 PARTS — コピペ部品ライブラリ", url: "https://osakenpiro.github.io/parts/" }, { ja: "バク運スカウター — 運力計測器", url: "https://osakenpiro.github.io/bakuun-scouter/" }] },
    { d: "2026-06-07", n: 2, items: [{ ja: "社会考証ビジュアライザ（ひとRe:）", url: "https://osakenpiro.github.io/shakai-vis/" }, { ja: "帝国運用カードゲーム ECG", url: "https://osakenpiro.github.io/ecg/" }] },
    { d: "2026-06-08", n: 1, items: [{ ja: "ワクワク — Wakuwaku Skeleton", url: "https://osakenpiro.github.io/wakuwaku/" }] },
    { d: "2026-06-09", n: 1, items: [{ ja: "文体測り — Bun-tai Hakari", url: "https://osakenpiro.github.io/buntai-hakari/" }] },
    { d: "2026-06-10", n: 2, items: [{ ja: "FABULA — システムの分類学", url: "https://osakenpiro.github.io/fabula/" }, { ja: "ステータス — RPG STATUS（経験値の現在地）", url: "https://osakenpiro.github.io/status/" }] },
    { d: "2026-06-13", n: 1, items: [{ ja: "MISOGI（禊）— 生態系M層消化器", url: null }] },
    { d: "2026-06-14", n: 14, label: "台帳創世 — 一斉登録", items: [] },
    { d: "2026-06-15", n: 1, items: [{ ja: "kokoro-guruguru（トマリぐるぐる / 魚乃ココロ受肉）", url: "https://osakenpiro.github.io/kokoro-guruguru/guruguru.html" }] },
    { d: "2026-06-18", n: 1, items: [{ ja: "あらいざらい (araizarai) — サブスク洗い出し＆解約ナビ", url: "https://osakenpiro.github.io/araizarai/" }] },
    { d: "2026-06-21", n: 3, items: [{ ja: "ものさし", url: "https://osakenpiro.github.io/monosashi/" }, { ja: "フリコ / FURIKO — 決断の振り子", url: "https://osakenpiro.github.io/furiko/" }, { ja: "三つ編み / Mitsuami", url: "https://osakenpiro.github.io/mitsuami/" }] },
    { d: "2026-07-04", n: 1, items: [{ ja: "Fable記 図鑑（思想の博物誌）", url: "https://osakenpiro.github.io/fable-ki/" }] },
    { d: "2026-07-07", n: 1, items: [{ ja: "僕のダンジョン", url: "https://osakenpiro.github.io/dungeon/" }] },
    { d: "2026-07-18", n: 2, items: [{ ja: "黒曜片（人類の素材図鑑 3D教科書 No.001）", url: "https://osakenpiro.github.io/kokuyouhen/" }, { ja: "護錆（人類の素材図鑑 3D教科書 No.002）", url: "https://osakenpiro.github.io/gosei/" }] },
    { d: "2026-07-26", n: 1, items: [{ ja: "還蹄（人類の素材図鑑 3D教科書・生物編）", url: "https://osakenpiro.github.io/kantei/" }] },
    { d: "2026-08-02", n: 87, label: "台帳創世 — 一斉登録", items: [] },
  ],
  // GEN:DDTL:END
};
