'use strict';
const TOPICS = {
  all: {name:'全身',groups:[], title:'体は、調節し続けている', text:'体内の状態を感知し、変化に応じて働きを調節する。この恒常性を入り口に、部位どうしの関係をたどります。', cards:[['恒常性・負のフィードバック','感知・調節・応答のつながりを知る。','https://openstax.org/books/anatomy-and-physiology-2e/pages/1-5-homeostasis'],['消化・吸収','取り込むことと、体内で利用することをつなぐ。','https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works']]},
  nervous:{name:'頭・神経',groups:['HEAD_NECK'],title:'頭部から、神経の仕組みへ',text:'ここは頭部・神経に関連づけた記録の入口です。画面の発光は頭頸部の筋肉で、脳や神経のモデルではありません。症状の原因や場所を推定しません。',cards:[]},
  circulation:{name:'循環・血液',groups:[],title:'全身をつなぐ記録',text:'血圧や血液検査は、全身に関わる情報としてまとめます。一つの測定値を、一つの臓器の状態と同一視しません。',cards:[['調節のつながり','恒常性の仕組みから見てみる。','https://openstax.org/books/anatomy-and-physiology-2e/pages/1-5-homeostasis']]},
  metabolism:{name:'腹部・代謝',groups:['ABDOMEN'],title:'取り込み、変え、使う',text:'消化・吸収の知識と、腹囲や健診の記録をたどる入口。発光は腹部の筋肉です。',cards:[['消化器の働き','消化管、肝臓、膵臓などの関係を読む。','https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works']]},
  kidney:{name:'腎臓・体液',groups:['BACK','ABDOMEN'],title:'濾過して、必要なものを戻す',text:'腎臓では血液の濾過と再吸収などが行われます。ここでは体液に関わる知識と記録を並べます。発光は体幹の関連領域で、腎臓の形状ではありません。',cards:[['腎臓の働き','濾過・再吸収と、水分などの調節を読む。','https://www.niddk.nih.gov/health-information/kidney-disease/kidneys-how-they-work']]},
  movement:{name:'筋肉・骨格',groups:['UPPER_ARM','UPPER_LEG','LOWER_LEG','BACK'],title:'動く体を、構造から見る',text:'筋肉をクリックすると名称・起始・停止・作用を確認できます。骨格は人体画面右上の「骨格」で重ねられます。',cards:[['運動フォーム','既存の型でえた・種目別表示を開く。','./index.html']]},
  immune:{name:'免疫・呼吸',groups:['CHEST','HEAD_NECK'],title:'関連する記録をたどる',text:'アレルギー、免疫療法、呼吸に関連づけた記録の入口。発光は胸部と頭頸部の筋肉です。免疫系や肺の形状は未収載です。',cards:[]},
  eye:{name:'目',groups:['HEAD_NECK'],title:'目に関する記録',text:'検査や手術の記録を、日付と出典からたどります。発光は頭頸部の筋群で、眼球そのものの表示ではありません。',cards:[]}
};
const $=id=>document.getElementById(id);
let topic='all', records=[], importVersion=0;
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function selectTopic(key){if(!Object.hasOwn(TOPICS,key))return;topic=key;document.querySelectorAll('#topics button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.key===key)));$('region-label').textContent=TOPICS[key].name;renderKnowledge();renderRecords();$('body').contentWindow.postMessage({type:'body-atlas-region',groups:TOPICS[key].groups},location.origin);}
for(const [key,t] of Object.entries(TOPICS)){const b=el('button',t.name);b.dataset.key=key;b.onclick=()=>selectTopic(key);$('topics').append(b);}
function renderKnowledge(){const t=TOPICS[topic],box=$('knowledge');box.replaceChildren(el('h3',t.title),el('p',t.text));for(const [title,text,url] of t.cards){const card=el('article',undefined,'card'),a=el('a','資料を読む ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';card.append(el('span','仕組みの資料','badge'),el('h4',title),el('p',text),a);box.append(card);}if(!t.cards.length)box.append(el('p','この領域の仕組みカードは、一次資料を確認しながら追加します。','empty'));}
function tab(name){for(const n of ['knowledge','records']){$(n).hidden=n!==name;$('tab-'+n).setAttribute('aria-selected',String(n===name));$('tab-'+n).tabIndex=n===name?0:-1;}}
for(const n of ['knowledge','records']){$('tab-'+n).onclick=()=>tab(n);$('tab-'+n).onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const other=e.key==='Home'?'knowledge':e.key==='End'?'records':n==='knowledge'?'records':'knowledge';tab(other);$('tab-'+other).focus();}};}
function validateRecords(data){if(!data||data.schema!=='body-records/v1'||!Array.isArray(data.records)||data.records.length>1000)throw Error('形式が違います。body-records/v1 のJSONを選んでください。');const ids=new Set();for(const r of data.records){if(!r||typeof r.id!=='string'||ids.has(r.id)||typeof r.title!=='string'||typeof r.source!=='string'||typeof r.evidence!=='string'||typeof r.date!=='string'||r.title.length>300||r.source.length>2000||!Array.isArray(r.topics)||r.topics.length===0||r.topics.some(t=>!Object.hasOwn(TOPICS,t)))throw Error('記録の日付・出典・領域・IDを確認してください。');ids.add(r.id);if(r.series!==undefined&&(!Array.isArray(r.series)||r.series.length>100||r.series.some(s=>!s||typeof s.date!=='string'||typeof s.value!=='string'||typeof s.unit!=='string')))throw Error('測定値の形式を確認してください。');if(r.note!==undefined&&typeof r.note!=='string')throw Error('説明文の形式を確認してください。');}return data.records;}
function renderRecords(){const box=$('record-list');box.replaceChildren();const list=records.filter(r=>topic==='all'||r.topics.includes(topic)).sort((a,b)=>(/^\d{4}-\d{2}-\d{2}$/.test(b.date)?b.date:'').localeCompare(/^\d{4}-\d{2}-\d{2}$/.test(a.date)?a.date:''));if(!list.length){box.append(el('p',records.length?'この領域には、まだ記録がありません。':'読み込んだ記録がここに並びます。','empty'));return;}for(const r of list){const card=el('article',undefined,'card');card.append(el('span',r.evidence,'badge'),el('h4',r.title),el('small',r.date));if(r.note)card.append(el('p',r.note));if(r.series){const table=el('table');const tr=el('tr');for(const h of ['測定日','値','単位']){const th=el('th',h);th.scope='col';tr.append(th);}table.append(tr);for(const s of r.series){const row=el('tr');row.append(el('td',s.date),el('td',s.value),el('td',s.unit));table.append(row);}card.append(table);}card.append(el('small','出典：'+r.source));box.append(card);}}
$('record-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const version=++importVersion;try{if(f.size>2*1024*1024)throw Error('2MB以下の記録ファイルを選んでください。');const next=validateRecords(JSON.parse(await f.text()));if(version!==importVersion)return;records=next;$('clear').hidden=false;$('import-status').textContent=records.length+'件を読み込みました。この画面内だけで表示中。';renderRecords();}catch(err){$('import-status').textContent='読込できませんでした：'+err.message;}finally{e.target.value='';}};
$('clear').onclick=()=>{importVersion++;records=[];$('clear').hidden=true;$('import-status').textContent='読み込んだ記録を消しました。';renderRecords();};
addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('body').contentWindow)return;if(e.data?.type==='body-atlas-ready'){$('model-status').textContent='ドラッグで回転・ピンチで拡大。筋肉をタップできます。';selectTopic(topic);}if(e.data?.type==='body-atlas-picked'){$('region-label').textContent='選択中：'+String(e.data.name).slice(0,200);}});
selectTopic('all');

addEventListener('pagehide',()=>{$('clear').click();});
