/* FINEPLAY 0.5 interface. The host engine decides permissions and scoring. */
(() => {
 'use strict';
 const tutorialRole=demo&&['asker','genie'].includes(new URLSearchParams(location.search).get('role'));
 const oldRender=render,oldBind=bind,oldIntro=intro,oldResult=result,oldRail=rail;
 const fmt=n=>Number(n||0).toFixed(2).replace(/\.00$/,''),labelList=t=>t.split(/[,、\n]/).map(x=>x.trim()).filter(Boolean);
 const q=e=>e.kind==='question'?R.questionText(e.text):e.text;
 const face=id=>`<span class="fp-face sm">${id===state.presenter?'<img src="assets/genie-face.png" alt="">':`<span class="fp-mark">${state.players.find(p=>p.id===id)?.role==='spectator'?'◉':'❋'}</span>`}</span>`;
 let applauseRound='',desired=0,flushTimer=null,wasDone=false;
 function applauseKey(){return P+'applause:'+room+':'+state.roundId+':'+state.applauseId+':'+me;}
 function syncApplause(){if(applauseRound!==state.applauseId){applauseRound=state.applauseId;desired=state.applause.mine;try{desired=Math.max(desired,Math.min(100,Number(sessionStorage.getItem(applauseKey()))||0));}catch{}}desired=Math.max(desired,state.applause.mine);}
 function scheduleFlush(){if(!flushTimer)flushTimer=setTimeout(flush,200);}
 function flush(){flushTimer=null;if(!state||!R.done(state)||state.locked||me===state.presenter)return;if(desired<=state.applause.mine)return;if(!ready||busy){if(ready)scheduleFlush();return;}send('applaud',{count:desired,applauseId:state.applauseId});if(desired>state.applause.mine)scheduleFlush();}
 function taps(){syncApplause();const mine=desired,self=me===state.presenter;return `<section class="panel applause-panel"><h2>${HAND} 出題者に、FinePlay！</h2><p>「${esc(state.reveal)}」のお題をくれた ${esc(person(state.presenter))} に、拍手を送ろう。</p><button id="applause-tap" class="primary applause-pad" ${self||!ready||mine>=100?'disabled':''}>${HAND}<strong>${self?'みんなの拍手':mine>=100?'100 FinePlay！':'FinePlay！'}</strong><span id="tap-count">${self?state.applause.total+' FinePlay':mine+' / 100'}</span></button><p class="applause-total">合計 <b>${state.applause.total}</b> FinePlay · 出題者に <b>＋${fmt(state.applause.points)}点</b></p><small>1人100回まで。100回＝1点。${mine>state.applause.mine?'送信待ちの拍手があります。':'連打もOK！'}</small></section>`;}
 function gradeButtons(e,problem=false){const self=problem?me===state.presenter:e.asker===me,target=problem?'problem':e.id,g=e.myGrade||0;return `<span class="grade-actions"><button class="vote${g===1?' voted':''}" data-grade="1" data-target="${esc(target)}" aria-pressed="${g===1}" ${self||busy||!ready||state.locked?'disabled':''}>${HAND} FinePlay${e.votes?' · '+e.votes:''}</button><button class="vote super${g===2?' voted':''}" data-grade="2" data-target="${esc(target)}" aria-pressed="${g===2}" ${self||busy||!ready||state.locked?'disabled':''}>✦ Super</button></span>`;}
 function hints(){return `<section class="hint-strip" aria-label="公開ヒント"><b>属性ヒント ${state.hintCount}個</b>${state.hints.map(x=>`<span class="hint-chip">${esc(x)}</span>`).join('')||'<small>まだありません</small>'}</section>`;}
 function privateCard(){if(me!==state.presenter||R.done(state))return '';return `<section class="private-card"><details><summary>自分だけの答え・属性メモ</summary><p class="private-answer">${esc(state.secretAnswer||'未登録')}</p><p class="small">ヒントにしたい属性だけ選ぶと、全員に公開されます。</p><div class="row">${state.attributes.map((x,i)=>`<button data-hint="${i}" ${state.hints.includes(x)||busy?'disabled':''}>${esc(x)}${state.hints.includes(x)?' · 公開済み':' → ヒント'}</button>`).join('')}</div></details>${button('private-edit','答え・属性を編集','quiet')}</section>`;}
 function observer(){return `<section class="panel spectator-panel"><h2>観戦中${state.locked?' · ネタバレはロック中':''}</h2><p>現在 ${state.progress}問。${state.locked?'質問・回答・答え合わせを見るか、自分で選べます。':'全員の質問と回答を見られます。'} 質問・解答は次のお題から参加できます。</p>${state.locked?button('unlock','質問・回答をアンロックする','primary'):''}${(state.phase==='lobby'||R.done(state))?button('join-player','次のお題は質問者で参加','quiet'):''}</section>`;}
 function commentPanel(){if(state.locked)return '';const es=state.entries;return `<section class="panel comment-panel"><div class="section-head"><h2>ひとこと・ふりかえり</h2>${es.length?button('comment-new','＋ コメント','quiet'):''}</div><div class="comment-feed">${state.comments.map(c=>{const e=es.find(e=>e.id===c.entryId);return `<article><a href="#history">Q${String(e.n).padStart(2,'0')} · ${esc(q(e)||'声での質問')}</a><p>${esc(c.text)}</p><small>${esc(person(c.author))}</small></article>`;}).join('')||'<p class="small">「前の質問がここで回収された！」など、質問や回答にひとこと。履歴からも書けます。</p>'}</div>${me===state.presenter&&es.filter(e=>e.kind==='question').length>=2?button('combo-new','つながった2問にCombo FinePlay','quiet'):''}${state.combos.length?`<p class="small">${state.combos.map(c=>'Combo：'+c.entryIds.map(id=>'Q'+es.find(e=>e.id===id).n).join(' ＋ ')+'（'+esc(person(c.asker))+'）').join('<br>')}</p>`:''}</section>`;}
 intro=()=>oldIntro().replace('<button class="primary wide"',`${room?'<label for="join-role">参加方法</label><select id="join-role"><option value="player">質問者として参加（途中なら観戦）</option><option value="spectator">観戦する</option></select>':''}<button class="primary wide"`);
 rail=()=>oldRail().replace('FRIENDS PREVIEW · 0.4.1','FRIENDS PREVIEW · 0.5').replace('</nav>','<a href="versions/pre-20260930/" target="_blank" rel="noopener">旧版で遊ぶ ↗</a></nav>');
 const numberField=(k,t,r)=>`<label for="rule-${k}">${t}</label><input id="rule-${k}" type="number" min="0" max="100" step="1" value="${r[k]}">`;
 settings=()=>{const next=state.players.filter(p=>p.online&&p.role==='player'),selected=state.round?next[(next.findIndex(p=>p.id===state.presenter)+1)%next.length]?.id:state.presenter,r=state.rules||R.defaults;return `<label for="presenter">出題する人</label><select id="presenter">${next.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.name)}</option>`).join('')}</select><label for="scope">お題の範囲</label><input id="scope" maxlength="80" value="${esc(state.scope)}"><label for="play-mode">遊び方</label><select id="play-mode"><option value="cooperative">協力 · 質問と回答を共有</option><option value="competitive" ${state.playMode==='competitive'?'selected':''}>対戦 · 自分の質問と回答だけ</option></select><label for="rule-preset">ルール</label><select id="rule-preset"><option value="casual">カジュアル · ワイワイ、解答制限なし</option><option value="dead" ${r.preset==='dead'?'selected':''}>デット · 得点と解答権の駆け引き</option></select><details id="rule-options"><summary>点数・解答権を調整する</summary><label for="rule-limit">デットの解答権</label><select id="rule-limit">${[['count','回数制限'],['points','点数を消費'],['none','回数制限なし・減点のみ']].map(([v,t])=>`<option value="${v}" ${(r.limit==='none'?'count':r.limit)===v?'selected':''}>${t}</option>`).join('')}</select><div class="rule-fields">${numberField('attempts','解答権の回数',r)}${numberField('guessCost','解答宣言の消費・減点',r)}${numberField('initialPoints','点数消費の初期持ち点',r)}${numberField('correctPoints','正解の加点',r)}${numberField('finePoints','FinePlayの加点',r)}${numberField('superPoints','Superの加点',r)}${numberField('comboPoints','Comboの追加加点',r)}</div></details><label for="mode">FinePlayの発表</label><select id="mode"><option value="live">その場で拍手</option><option value="sealed" ${state.mode==='sealed'?'selected':''}>答え合わせの後</option></select><p class="small">点数消費では「その場で」を使用。質問は減点なし。解答宣言は送信時に権利を使い、取り消しても戻りません。</p><div id="initial-answer-row" ${selected===me?'':'hidden'}><label for="initial-answer">お題の答え <small>任意・出題者だけに表示</small></label><input id="initial-answer" type="password" maxlength="200" autocomplete="off" ${selected===me?'':'disabled'}></div><p class="small">次の準備画面で、出題者が答えと属性を登録できます。</p>${button('start','お題を用意する →','primary wide',next.length<2)}`;};
 startRound=()=>{const r={preset:$('#rule-preset').value,limit:$('#rule-limit').value};for(const k of ['attempts','guessCost','initialPoints','correctPoints','finePoints','superPoints','comboPoints'])r[k]=Number($('#rule-'+k).value);send('start',{presenter:$('#presenter').value,scope:$('#scope').value,mode:$('#mode').value,playMode:$('#play-mode').value,secretAnswer:$('#presenter').value===me?$('#initial-answer').value:'',rules:r});};
 preparation=()=>`<section class="panel scene preparation"><h2>${me===state.presenter?'お題と、属性を用意しよう。':'出題者がお題を準備しています。'}</h2>${me===state.presenter?`<form id="prepare-form"><label for="prepare-answer">答え <small>自分だけのメモ</small></label><input id="prepare-answer" maxlength="200" autocomplete="off"><label for="prepare-labels">属性ラベル <small>任意 · カンマで区切る・12個まで</small></label><textarea id="prepare-labels" rows="2" placeholder="食べもの、植物、緑色、水中"></textarea><p class="small">自分用の参考メモです。属性はプレイ中に選んだものだけヒントとして公開できます。答えを空欄にしても開始できます。</p>${button('begin','準備できた・質問を始める →','primary wide')}</form>`:`<p>${esc(person(state.presenter))} が準備を終えたら始まります。</p>`}</section>`;
 problemFineplay=()=>state.phase==='preparing'||state.locked||tutorialRole?'':`<section class="panel problem-fp"><b>この問題にFinePlay</b>${gradeButtons(state.problem,true)}${state.hidden?'<small>認定は終了後に発表</small>':''}</section>`;
 resultStats=()=>{if(!state.result||tutorialRole)return '';const c=state.result.counts;return `<section class="panel result-stats"><h2>今回の記録 · ${state.playMode==='competitive'?'対戦':'協力'} / ${state.rules.preset==='dead'?'デット':'カジュアル'}</h2><p>質問 ${c.questions} ＋ 判定済みの解答 ${c.guesses} · ヒント ${state.hintCount}個</p><div class="stats-scroll"><table><thead><tr><th>メンバー</th><th>質問</th><th>解答 / 使用権</th><th>FinePlay / Super / Combo</th><th>${state.rules.preset==='dead'?'得点':'拍手ポイント'}</th></tr></thead><tbody>${state.result.players.filter(p=>!p.spectator).map(p=>`<tr><th>${esc(p.name)}${p.presenter?'（出題）':''}</th><td>${p.questions}</td><td>${p.guesses} / ${p.used}</td><td>${p.fineplays} / ${p.superFineplays} / ${p.combos}<small>受けた票：質問 ${p.questionVotes}・解答 ${p.guessVotes}・問題 ${p.problemVotes}</small></td><td><b>${fmt(p.score)}</b></td></tr>`).join('')}</tbody></table></div><p class="small">認定は1投稿につき最高の種類だけ加点。SuperはFinePlayの代わりに＋${state.rules.superPoints}、Comboは2問のつながりへ＋${state.rules.comboPoints}。カジュアルは減点・順位なし。</p></section>`;};
 if(!tutorialRole){
  members=()=>`<section class="panel members fp-members"><div class="section-head"><h2>メンバー ${state.players.length}人</h2>${!demo?button('invite','招待URLをコピー','quiet'):''}</div><div class="roster">${state.players.map(p=>`<div class="member${p.online?'':' offline'}">${face(p.id)}<b>${esc(p.name)}${p.id===me?'<small>あなた</small>':''}</b><small>${p.id===state.presenter?'魔人（回答）':p.role==='spectator'?'観戦':'質問'}${p.online?'':' · 接続待ち'}</small></div>`).join('')}</div>${(state.phase==='lobby'||R.done(state))?button('toggle-role',state.spectator?'次のお題は質問者で':'次のお題は観戦する','quiet'):''}</section>`;
  scene=()=>{const p=state.pending,last=state.entries.at(-1),isPresenter=me===state.presenter,e=p&&!p.private?p:last;let action='';if(state.spectator)action=observer();else if(p?.private)action='<p class="wait-label">ほかの質問者への回答中です。内容は対戦終了後に公開されます。</p>';else if(p&&isPresenter)action=`<div class="answers ${p.kind==='guess'?'two':'six'}">${(p.kind==='guess'?['correct','incorrect']:['yes','no','partly','probably','probablyNot','unknown']).map(k=>button('answer-'+k,`<span class="answer-icon">${icon[k]}</span><b>${R.labels[k]}</b>`,k)).join('')}</div>`;else if(p)action=demo?button('turn-to-answer','回答役に切り替える →','primary wide'):`<p class="wait-label">${esc(person(state.presenter))} の回答待ち</p>`;else if(isPresenter)action=demo?button('demo-nextquestion','次のサンプル質問へ →','primary wide'):'<p class="wait-label">質問を待っています。</p>';else action=`<form id="question-form"><label for="question">質問メモ <small>任意・声だけでもOK</small></label><div class="question-input"><input id="question" value="${esc(draft)}" maxlength="200" placeholder="例：外で使うもの"><span id="question-suffix" aria-hidden="true" ${/[?？]$/.test(draft.trim())?'hidden':''}>？</span></div><div class="row">${button('ask','この質問をする →','primary grow')}${button('guess','答えがわかった','dark',!state.allowance.canGuess)}</div></form>`;const r=state.rules,a=state.allowance,limit=r.preset==='dead'?`<p class="rights-line">解答宣言 −${r.guessCost} · 正解 ＋${r.correctPoints}${a.left!==null?' · 解答権あと '+a.left+'回':''}${a.balance!==null?' · 持ち点 '+a.balance:''}${state.hidden?' · 加点は終了後に発表':''}</p>`:'';
   return `${hints()}${privateCard()}<section class="panel scene fp-scene"><div class="fp-turn">${face(me)}<strong>${state.spectator?'あなたは観戦者':isPresenter?'あなたが回答する番':p?'回答待ち':'あなたが質問できます'}</strong><span class="rule-badge">${r.preset==='dead'?'デット':'カジュアル'} · ${state.playMode==='competitive'?'対戦':'協力'}</span></div>${e?`<article class="fp-card"><header class="fp-card-head">${face(e.asker)}<b>${esc(person(e.asker))}</b><span>${e.kind==='guess'?'の解答宣言':'の質問'}</span><span class="fp-qno">Q${String(e.n).padStart(2,'0')}</span></header><h2>${esc(q(e)||'声での質問（本文未記録）')}</h2>${!p||p.private?`<div class="fp-card-foot"><span class="answer-chip ${e.answer}">${R.labels[e.answer]}</span>${gradeButtons(e)}</div>`:''}</article>`:'<p class="wait-label">何から、聞こう。</p>'}${limit}${action}<details class="turn-tools"><summary>訂正・その他</summary><div class="row">${p&&!p.private&&(isPresenter||owner||p.asker===me)?button('cancel','取り消す','quiet'):''}${!p&&isPresenter&&state.entries.length?button('undo','直前の回答を訂正','quiet'):''}${isPresenter?button('reveal','お題を公開して終了','quiet'):''}</div></details></section>${commentPanel()}`;};
  result=()=>state.locked?`${hints()}${observer()}`:`${oldResult()}${taps()}${commentPanel()}${state.spectator?observer():''}`;
  fineplay=()=>'';
  historyPanel=()=>{let rows=state.entries.filter(e=>(filter==='all'||(filter==='fp'?e.votes>0||e.myVote:e.answer===filter))&&(!search||[q(e),person(e.asker),R.labels[e.answer]].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())));if(order==='new')rows=[...rows].reverse();return `<section class="panel history" id="history"><div class="section-head"><h2>${R.done(state)?'質問・解答の全履歴':'ここまでの質問'} ${state.entries.length}件</h2><button id="history-order" class="quiet">${order==='old'?'古い順 ↓':'新しい順 ↓'}</button></div>${state.playMode==='competitive'&&!R.done(state)?'<p class="small">対戦中は自分の履歴だけ表示されます（出題者・アンロックした観戦者を除く）。</p>':''}<div class="history-filters"><input id="history-search" aria-label="履歴を検索" value="${esc(search)}" placeholder="質問・名前で探す"><select id="history-filter" aria-label="履歴を絞り込む">${[['all','すべて'],...Object.entries(R.labels),['fp','FinePlay']].map(([k,t])=>`<option value="${k}" ${k===filter?'selected':''}>${t}</option>`).join('')}</select></div><div class="history-list" tabindex="0" aria-label="質問と回答の履歴">${rows.map(e=>`<details class="history-item compact-clue" data-entry="${esc(e.id)}"><summary><span class="history-number">${e.n}</span><span class="clue-main"><span class="clue-text">${e.kind==='guess'?'解答：':''}${esc(q(e)||'声での質問（本文未記録）')}</span><small>${esc(person(e.asker))}${e.grade===2?' · ✦ Super':e.grade===1?' · FinePlay':''}</small></span><span class="answer-chip ${e.answer}">${R.labels[e.answer]}</span></summary><div class="clue-detail">${gradeButtons(e)}<div class="row"><button data-comment="${esc(e.id)}" class="quiet">ひとこと</button>${e.kind==='question'&&(me===state.presenter||me===e.asker)?`<button data-note="${esc(e.id)}" class="quiet">メモを直す</button>`:''}</div>${state.comments.filter(c=>c.entryId===e.id).map(c=>`<p class="clue-comment">${esc(c.text)} <small>— ${esc(person(c.author))}</small></p>`).join('')}</div></details>`).join('')||'<p class="small">表示できる履歴はまだありません。</p>'}</div>${state.locked?'<p class="small">観戦のアンロック後に表示されます。</p>':''}</section>`;};
 }
 function commentModal(id){const es=state.entries;modal(`<h2>質問・回答にひとこと</h2><label for="comment-entry">どの質問・解答？</label><select id="comment-entry">${es.map(e=>`<option value="${esc(e.id)}" ${e.id===id?'selected':''}>Q${e.n} ${esc(q(e)||'声での質問')}</option>`).join('')}</select><label for="comment-text">コメント</label><textarea id="comment-text" rows="3" maxlength="200" placeholder="Q03の質問がここで回収された！"></textarea><div class="row"><button id="comment-send" class="primary">残す</button><button id="modal-close">戻る</button></div>`);on('comment-send',()=>send('comment',{entryId:$('#comment-entry').value,text:$('#comment-text').value}));$('#comment-text').focus();}
 bind=()=>{oldBind();on('unlock',()=>{modal('<h2>質問・回答をアンロックする？</h2><p>全員の推理を見ると、ネタバレを含みます。このお題では元に戻せません。出題者の正解メモ・未公開の属性は表示されません。</p><button id="unlock-confirm" class="primary">アンロックする</button><button id="modal-close">戻る</button>');on('unlock-confirm',()=>send('unlock'));});on('join-player',()=>send('role',{role:'player'}));on('toggle-role',()=>send('role',{role:state.spectator?'player':'spectator'}));
  if($('#prepare-form'))$('#prepare-form').onsubmit=e=>{e.preventDefault();send('begin',{text:$('#prepare-answer').value,attributes:labelList($('#prepare-labels').value)});};
  on('private-edit',()=>{modal(`<h2>自分だけの答え・属性メモ</h2><label for="private-answer">答え</label><input id="private-answer" maxlength="200" value="${esc(state.secretAnswer)}"><label for="private-labels">属性ラベル</label><textarea id="private-labels" rows="3">${esc(state.attributes.join('、'))}</textarea><p class="small">公開済みの属性ヒントは消せません。</p><div class="row"><button id="private-save" class="primary">保存する</button><button id="modal-close">戻る</button></div>`);on('private-save',()=>send('setAnswer',{text:$('#private-answer').value,attributes:labelList($('#private-labels').value)}));});
  document.querySelectorAll('[data-hint]').forEach(b=>b.onclick=()=>send('hint',{label:state.attributes[Number(b.dataset.hint)]}));
  document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{const target=b.dataset.target,e=target==='problem'?state.problem:state.entries.find(e=>e.id===target),g=Number(b.dataset.grade);send(target==='problem'?'voteProblem':'vote',{entryId:target,grade:e.myGrade===g?0:g});});
  document.querySelectorAll('[data-comment]').forEach(b=>b.onclick=()=>commentModal(b.dataset.comment));on('comment-new',()=>commentModal(state.entries.at(-1)?.id));
  on('combo-new',()=>{const es=state.entries.filter(e=>e.kind==='question'),options=es.map(e=>`<option value="${esc(e.id)}">Q${e.n} ${esc(person(e.asker))}：${esc(q(e)||'声での質問')}</option>`).join('');modal(`<h2>Combo FinePlay</h2><p>同じ質問者の、意味がつながった2問を出題者が認定します。</p><label for="combo-first">前の質問</label><select id="combo-first">${options}</select><label for="combo-second">つながる質問</label><select id="combo-second">${options}</select><div class="row"><button id="combo-save" class="primary">認定する</button><button id="combo-remove">認定を取り消す</button><button id="modal-close">戻る</button></div>`);const combo=value=>send('combo',{entryIds:[$('#combo-first').value,$('#combo-second').value],value});on('combo-save',()=>combo(true));on('combo-remove',()=>combo(false));});
  on('applause-tap',()=>{syncApplause();desired=Math.min(100,desired+1);try{sessionStorage.setItem(applauseKey(),String(desired));}catch{}const b=$('#applause-tap');$('#tap-count').textContent=desired+' / 100';if(desired===100)b.disabled=true;scheduleFlush();});
  if($('#question'))$('#question').oninput=e=>{draft=e.target.value;$('#question-suffix').hidden=/[?？]$/.test(draft.trim());};
  if(!tutorialRole)on('share',()=>{const c=state.result?.counts;if(!c)return;const text=`FINEPLAY · ROUND ${state.round}\n${state.playMode==='competitive'?'対戦':'協力'} / ${state.rules.preset==='dead'?'デット':'カジュアル'}\n答え：||${safeDiscord(state.reveal)}||\n質問 ${c.questions}・解答 ${c.guesses}・ヒント ${state.hintCount}\n${state.result.players.filter(p=>!p.spectator).map(p=>safeDiscord(p.name)+': '+fmt(p.score)+'点 / 質問 '+p.questions+'・FP '+p.fineplays+'・Super '+p.superFineplays+'・Combo '+p.combos).join('\n')}\n出題者への拍手 ${state.applause.total}（＋${fmt(state.applause.points)}点）`;modal(`<h2>Discord用の結果</h2><textarea id="result-text" rows="10" readonly>${esc(text)}</textarea><button id="result-copy" class="primary">コピー</button><button id="modal-close">閉じる</button>`);on('result-copy',()=>copy(text));});
 };
 render=()=>{const open=[...document.querySelectorAll('.compact-clue[open]')].map(e=>e.dataset.entry),privateOpen=$('.private-card details')?.open,ruleOpen=$('#rule-options')?.open;oldRender();if(ruleOpen&&$('#rule-options'))$('#rule-options').open=true;document.body.classList.add('enhanced-050');for(const id of open)document.querySelector(`[data-entry="${CSS.escape(id)}"]`)?.setAttribute('open','');if(privateOpen&&$('.private-card details'))$('.private-card details').open=true;const foot=$('footer');if(foot){if(foot.firstChild.nodeType===3)foot.firstChild.textContent='FINEPLAY 0.5 ';if(!foot.querySelector('.old-version'))foot.insertAdjacentHTML('beforeend','<a class="old-version" href="versions/pre-20260930/" target="_blank" rel="noopener">旧版で遊ぶ ↗</a>');}if(state&&wasDone&&!R.done(state)){desired=0;try{sessionStorage.removeItem(applauseKey());}catch{}}wasDone=!!state&&R.done(state);if(state&&R.done(state)&&!state.locked){syncApplause();if(desired>state.applause.mine)scheduleFlush();}};
 render();
})();
