/* Device-local presentation only. Confirmed, role-filtered host views are the event source. */
(()=>{'use strict';
 const key=P+'feedback-look',presets={fine:{label:'FinePlay!',icon:HAND},hot:{label:'熱盛!!',icon:'<span class="praise-symbol" aria-hidden="true">♨</span>'},rare:{label:'珍プレー!!',icon:'<span class="praise-symbol" aria-hidden="true">✧</span>'}};
 let options={preset:'fine',volume:12,sound:false};try{const saved=JSON.parse(localStorage.getItem(key)||'{}');if(presets[saved.preset])options.preset=saved.preset;if(Number.isFinite(saved.volume))options.volume=Math.max(0,Math.min(30,saved.volume));}catch{}
 let prev=null,viewKey='',active=null,praiseTimer=null,queued=null,audio=null,chimeTimer=null,lastChime=-Infinity,settingsOpen=false,oldCommentsOpen=false;
 const soundQueue=new Set(),voices=new Set(),tones={correct:[659,880],incorrect:[392,330],fine:[784,988],question:[523],comment:[659]},priority=['correct','incorrect','fine','question','comment'];
 const unread=new Map(),metrics={pulses:0,chimes:0,audioContexts:0,coalesced:0,soundMerged:0,soundKinds:{correct:0,incorrect:0,fine:0,question:0,comment:0}};window.__fineplayFeedback={metrics,unread};
 const oldRender=render,oldHistory=historyPanel,oldBind=bind;
 const save=()=>{try{localStorage.setItem(key,JSON.stringify({preset:options.preset,volume:options.volume}));}catch{}};
 function sortedComments(){return state.comments.map((c,i)=>({...c,ordinal:i})).sort((a,b)=>(b.at||0)-(a.at||0)||(b.seq??b.ordinal)-(a.seq??a.ordinal)||b.id.localeCompare(a.id));}
 const comment=c=>{const e=state.entries.find(e=>e.id===c.entryId);if(!e)return '';return `<article data-comment-id="${esc(c.id)}"><a href="#history" data-comment-jump="${esc(e.id)}">Q${String(e.n).padStart(2,'0')} · ${esc(e.kind==='question'?R.questionText(e.text):e.text||'声での質問')}</a><p>${esc(c.text)}</p><small>${esc(person(c.author))}</small></article>`;};
 function paintComments(){const feed=$('.comment-feed');if(!feed)return;const cs=sortedComments();feed.innerHTML=`<div class="latest-comments">${cs.slice(0,3).map(comment).join('')}</div>${cs.length>3?`<details class="older-comments" ${oldCommentsOpen?'open':''}><summary>以前のコメント ${cs.length-3}件</summary><div>${cs.slice(3).map(comment).join('')}</div></details>`:''}`;const older=$('.older-comments');if(older)older.ontoggle=()=>{oldCommentsOpen=older.open;};document.querySelectorAll('[data-comment-jump]').forEach(a=>a.onclick=e=>{e.preventDefault();jumpEntry(a.dataset.commentJump);});}
 historyPanel=()=>state.locked?`<section class="panel history" id="history"><div class="section-head"><h2>ここまでの質問 ${state.progress}件</h2></div><p class="small">観戦の履歴はアンロック後に表示されます。</p><button id="history-unlock" class="quiet">履歴を表示</button></section>`:oldHistory();
 bind=()=>{oldBind();on('history-unlock',()=>$('#unlock')?.click());};
 function paintPresets(){document.querySelectorAll('.history-item[data-entry]').forEach(row=>{const e=state?.entries.find(x=>x.id===row.dataset.entry),b=row.querySelector('.clue-detail [data-grade="1"]');if(state.playMode==='cooperative'&&!state.locked&&e?.asker!==me&&b){b.classList.add('history-quick-fp');b.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();});row.querySelector('summary').append(b);}});const p=presets[options.preset];document.querySelectorAll('[data-grade="1"]').forEach(b=>{const target=b.dataset.target,e=target==='problem'?state?.problem:state?.entries.find(x=>x.id===target);b.innerHTML=p.icon+' '+p.label+(e?.votes?' · '+e.votes:'');b.dataset.look=options.preset;});document.querySelectorAll('.history-item[data-entry]').forEach(row=>{const e=state?.entries.find(e=>e.id===row.dataset.entry),small=row.querySelector('.clue-main small');if(e?.grade===1&&small)small.innerHTML=esc(person(e.asker))+' · <span class="history-praise">'+p.icon+' '+p.label+'</span>';});const applause=$('#applause-tap');if(applause){applause.querySelector('.hand,.praise-symbol')?.remove();applause.insertAdjacentHTML('afterbegin',p.icon);const title=$('.applause-panel h2');if(title)title.innerHTML=p.icon+' 出題者に、'+p.label;const text=applause.querySelector('strong');if(text&&me!==state.presenter)text.textContent=$('#tap-count').textContent.startsWith('100 /')?'100 '+p.label:p.label;}}
 function paintSettings(){const footer=$('footer');if(!footer||!state)return;footer.insertAdjacentHTML('beforeend',`<details class="feedback-settings" ${settingsOpen?'open':''}><summary>演出・通知</summary><div class="feedback-settings-body"><label for="feedback-look">FinePlayの見た目</label><select id="feedback-look">${Object.entries(presets).map(([id,p])=>`<option value="${id}" ${id===options.preset?'selected':''}>${p.label}</option>`).join('')}</select><label class="sound-choice"><input id="feedback-sound" type="checkbox" ${options.sound?'checked':''}>通知音</label><label for="feedback-volume">音量</label><input id="feedback-volume" type="range" min="0" max="30" value="${options.volume}" aria-label="通知音の音量"><small>この端末だけの設定</small></div></details>`);$('.feedback-settings').ontoggle=e=>{settingsOpen=e.target.open;};$('#feedback-look').onchange=e=>{options.preset=e.target.value;save();paintPresets();};$('#feedback-volume').oninput=e=>{options.volume=Number(e.target.value);save();};$('#feedback-sound').onchange=async e=>{options.sound=e.target.checked;if(!options.sound){quietSound();return;}if(!e.isTrusted||!navigator.userActivation?.isActive){options.sound=false;e.target.checked=false;return;}try{if(!audio){audio=new AudioContext();metrics.audioContexts++;}await audio.resume();}catch{options.sound=false;e.target.checked=false;toast('この端末では通知音を開始できませんでした。');}};}
 function quietSound(){if(chimeTimer)clearTimeout(chimeTimer);chimeTimer=null;soundQueue.clear();for(const node of voices){try{node.stop();}catch{}}voices.clear();}
 function playTone(kind){const t=audio.currentTime,notes=tones[kind],peak=.024*options.volume/30;notes.forEach((frequency,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),at=t+i*.075;osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(peak,at+.008);gain.gain.exponentialRampToValueAtTime(.0001,at+.064);gain.gain.linearRampToValueAtTime(0,at+.070);osc.connect(gain).connect(audio.destination);voices.add(osc);osc.start(at);osc.stop(at+.075);osc.onended=()=>{voices.delete(osc);osc.disconnect();gain.disconnect();};});metrics.chimes++;metrics.soundKinds[kind]++;}
 function chime(kind){if(!options.sound||!audio||audio.state!=='running'||document.hidden||options.volume===0)return;if(chimeTimer)metrics.soundMerged++;soundQueue.add(kind);if(chimeTimer)return;chimeTimer=setTimeout(()=>{chimeTimer=null;const chosen=priority.find(k=>soundQueue.has(k));soundQueue.clear();if(!chosen||document.hidden||!options.sound||options.volume===0||audio?.state!=='running'||performance.now()-lastChime<1000)return;lastChime=performance.now();playTone(chosen);},180);}
 document.addEventListener('fineplay:public-feedback',event=>{if(['fine','applause'].includes(event.detail?.kind)&&state&&!state.locked&&!state.hidden&&(state.playMode==='cooperative'||R.done(state)))chime('fine');});
 function praise(id,grade){if(document.hidden)return;queued={id,grade};if(praiseTimer||active){metrics.coalesced++;return;}praiseTimer=setTimeout(()=>{praiseTimer=null;if(document.hidden||!queued)return;active={...queued,start:performance.now()};queued=null;metrics.pulses++;paintPraise();setTimeout(()=>{active=null;queued=null;document.querySelectorAll('.received-praise').forEach(e=>{e.classList.remove('received-praise');e.removeAttribute('data-praise-start');});},850);},140);}
 function praiseTarget(id){return document.querySelector(`[data-card-entry="${CSS.escape(id)}"] .grade-actions`)||document.querySelector(`[data-entry="${CSS.escape(id)}"] > summary`);}
 function paintPraise(){if(!active||document.hidden||performance.now()-active.start>=850)return;const target=praiseTarget(active.id);if(!target)return;target.classList.add('received-praise');target.dataset.praiseStart=String(active.start);target.style.setProperty('--praise-delay',`-${performance.now()-active.start}ms`);}
 function seed(){prev={rev:state.rev,phase:state.phase,hidden:state.hidden,problem:{votes:state.problem.votes,grade:state.problem.grade},pending:state.pending?.id,entries:new Map(state.entries.map(e=>[e.id,{votes:e.votes,grade:e.grade}])),comments:new Set(state.comments.map(c=>c.id)),hints:new Set(state.hints)};}
 function confirmedChanges(){if(!state||!ready){prev=null;active=null;queued=null;if(praiseTimer)clearTimeout(praiseTimer);praiseTimer=null;quietSound();return;}const nextKey=[room,state.roundId,me,state.locked].join(':');if(nextKey!==viewKey||!prev){viewKey=nextKey;unread.clear();active=null;queued=null;if(praiseTimer)clearTimeout(praiseTimer);praiseTimer=null;quietSound();seed();return;}if(state.rev<=prev.rev)return;
 const publicNow=!state.locked&&(state.playMode==='cooperative'||R.done(state));
 for(const e of state.entries){const old=prev.entries.get(e.id),received=old&&e.asker===me&&!prev.hidden&&!state.hidden&&(e.votes>old.votes||e.grade>old.grade);if(received){if(e.kind==='question'&&state.phase==='playing')praise(e.id,e.grade);if(publicNow)chime('fine');}if(!old&&e.asker===me&&prev.pending===e.id&&prev.phase==='playing')unread.set('answer:'+e.id,{kind:'answer',id:e.id});if(!old&&e.kind==='guess'&&publicNow&&prev.phase==='playing'){if(e.answer==='correct'&&state.phase==='solved'&&e.id===state.entries.at(-1)?.id)chime('correct');else if(e.answer==='incorrect'&&prev.pending===e.id)chime('incorrect');}}
 if(publicNow&&!prev.hidden&&!state.hidden&&me===state.presenter&&(state.problem.votes>prev.problem.votes||state.problem.grade>prev.problem.grade))chime('fine');
 if(publicNow&&state.phase==='playing'&&state.pending?.kind==='question'&&state.pending.asker!==me&&state.pending.id!==prev.pending)chime('question');
 for(const c of state.comments)if(!prev.comments.has(c.id)&&c.author!==me){unread.set('comment:'+c.id,{kind:'comment',id:c.id,entryId:c.entryId});if(publicNow)chime('comment');}
 for(const label of state.hints)if(!prev.hints.has(label)&&me!==state.presenter)unread.set('hint:'+label,{kind:'hint',id:label});
 for(const [k,n]of unread)if(n.kind==='hint'?!state.hints.includes(n.id):n.kind==='answer'?!state.entries.some(e=>e.id===n.id):!state.comments.some(c=>c.id===n.id))unread.delete(k);
 seed();}
 function jumpEntry(id){const target=document.querySelector(`[data-entry="${CSS.escape(id)}"]`);if(target){target.open=true;target.scrollIntoView({block:'center',behavior:'instant'});}else{const card=document.querySelector(`[data-card-entry="${CSS.escape(id)}"]`);card?.scrollIntoView({block:'center',behavior:'instant'});}}
 function paintUnread(){const link=$('.history-jump');if(!link)return;paintUnreadCount();link.onclick=e=>{if(!unread.size)return;e.preventDefault();const [key,n]=[...unread].at(-1);if(n.kind==='hint'){const target=[...document.querySelectorAll('.hint-strip .hint-chip')].find(e=>e.dataset.hintLabel===n.id);target?.scrollIntoView({block:'center',behavior:'instant'});}else if(n.kind==='comment'){const target=document.querySelector(`[data-comment-id="${CSS.escape(n.id)}"]`);if(target){target.closest('.older-comments')?.setAttribute('open','');target.scrollIntoView({block:'center',behavior:'instant'});}else jumpEntry(n.entryId);}else{filter='all';search='';render();jumpEntry(n.id);}unread.delete(key);paintUnreadCount();paintHintUnread();};}
 function paintHintUnread(){document.querySelectorAll('.hint-strip .hint-chip').forEach((chip,i)=>{const label=state.hints[i];chip.dataset.hintLabel=label;chip.querySelector('.hint-new')?.remove();chip.classList.toggle('hint-unread',unread.has('hint:'+label));if(unread.has('hint:'+label))chip.insertAdjacentHTML('beforeend','<small class="hint-new">NEW</small>');});}
 function paintUnreadCount(){const link=$('.history-jump');if(!link)return;link.querySelector('.unread-badge')?.remove();link.classList.toggle('has-unread',!!unread.size);if(unread.size){link.insertAdjacentHTML('beforeend',`<span class="unread-badge" aria-hidden="true">${unread.size}</span>`);link.setAttribute('aria-label',`未読の回答・コメント・ヒント ${unread.size}件を表示`);}else link.removeAttribute('aria-label');}
 render=()=>{const x=scrollX,y=scrollY,focus=document.activeElement,selection=focus?.selectionStart!==undefined?{start:focus.selectionStart,end:focus.selectionEnd,direction:focus.selectionDirection}:null,focusedId=focus?.id,historyScroll=$('.history-list')?.scrollTop,olderScroll=$('.older-comments > div')?.scrollTop,currentKey=viewKey;settingsOpen=$('.feedback-settings')?.open??settingsOpen;oldCommentsOpen=$('.older-comments')?.open??oldCommentsOpen;confirmedChanges();oldRender();paintComments();paintPresets();paintSettings();paintUnread();paintHintUnread();paintPraise();if(currentKey===viewKey){if(historyScroll!==undefined&&$('.history-list'))$('.history-list').scrollTop=historyScroll;if(olderScroll!==undefined&&$('.older-comments > div'))$('.older-comments > div').scrollTop=olderScroll;if(focusedId&&$('#'+focusedId)){const e=$('#'+focusedId);e.focus({preventScroll:true});if(selection)try{e.setSelectionRange(selection.start,selection.end,selection.direction);}catch{}}scrollTo(x,y);}};
 document.addEventListener('visibilitychange',()=>{if(document.hidden){if(praiseTimer)clearTimeout(praiseTimer);praiseTimer=null;queued=null;active=null;quietSound();document.querySelectorAll('.received-praise').forEach(e=>e.classList.remove('received-praise'));}});
 render();
})();
