/* View-only integration of the authoritative fineplay-fp/1 contract. */
(()=>{'use strict';
const prior=render,q=s=>document.querySelector(s);let controller=null,currentRoom='',connection=null;
function ensure(){if(currentRoom!==room){controller?.dispose();controller=null;currentRoom=room;connection=null;}if(!controller)controller=FinePlayCelebration.createViewController({playSound:args=>window.FPSound?.enqueue(args)??false});}
function badge(h){if(!h||(!h.super&&!h.ultra))return null;const tier=h.ultra?'ultra':'super',b=document.createElement('span');b.className='fp-honor-badge';b.dataset.honorTier=tier;b.setAttribute('aria-label',(h.ultra?'Ultra':'Super')+'FinePlay・ボーナス '+h.bonusPoints+'点');b.append(FinePlayCelebration.createIcon({tier}));const value=document.createElement('small');value.textContent='+'+h.bonusPoints;b.append(value);return b;}
function paint(){if(!state||!['fineplay-fp/1','fineplay-fp/2','fineplay-fp/3'].includes(state.fpContractVersion)||state.fpRuleVersion!=='distinct-donors/1'||state.locked||state.hidden)return;const topic=badge(state.problem?.honors);if(topic)q('#layout-topic .attrs-fp-trigger')?.append(topic);for(const row of document.querySelectorAll('#history .history-item[data-entry]')){const entry=state.entries.find(e=>e.id===row.dataset.entry),b=badge(entry?.honors);if(b)row.querySelector(':scope>summary')?.append(b);}const debt=state.wallet?.debt;if(Number.isFinite(debt)&&debt>0){const wallet=q('.layout-wallet');if(wallet){const note=document.createElement('small');note.textContent='返済 '+debt;note.className='fp-wallet-debt';wallet.append(note);}}}
render=()=>{prior();ensure();const live=owner?peer:conn,replaced=!!connection&&live!==connection;if(replaced)controller.suspend();if(live)connection=live;const transient=!demo&&!owner&&!ready&&!replaced&&!connecting&&!error&&conn?.open===true&&stateReceiver?.status==='syncing';const viewKey=[room,me,state?.role||'',!!state?.spectator].join(':');controller.observe(state,{ready:!!ready&&!!state,viewKey,transient});paint();};
window.__fineplayHonors={inspect:()=>controller?.inspect(),resolveSnapshots:()=>({result:R.resolveSnapshot(state,state.result),lastFinalized:R.resolveSnapshot(state,state.lastFinalized),history:state.history.map(h=>R.resolveSnapshot(state,h))})};addEventListener('pagehide',()=>controller?.dispose());render();
})();
