/* Shared final UI glue: engine projections remain the source of score and achievements. */
(()=>{'use strict';
 const previousRender=render,knownAchievements={firstQuestion:'はじめの質問',fineplay:'FinePlay獲得',superFineplay:'Super獲得',ultraFineplay:'Ultra FinePlay獲得',correctGuess:'正解！',tenQuestionsOrFewer:'10問以内の正解',hundredApplause:'100拍手をもらった'},themes={fine:{label:'FinePlay!',icon:HAND},hot:{label:'熱盛!!',icon:'<span class="praise-symbol" aria-hidden="true">♨</span>'},rare:{label:'珍プレー!!',icon:'<span class="praise-symbol" aria-hidden="true">✧</span>'}};
 let achievementKey='',seeded=false,previousCodes=new Set();const pulses=new Map();
 const fmt=n=>String(Math.round(Number(n||0)*100)/100);

 function patchSettings(){const field=$('#play-mode'),group=$('.setup-rules.whole-rules');if(!field||!group)return;field.hidden=true;field.setAttribute('aria-hidden','true');group.querySelector('label[for="play-mode"]')?.remove();let picker=group.parentElement.querySelector('.integration-play-picker');if(!picker){picker=document.createElement('fieldset');picker.className='play-picker integration-play-picker';picker.innerHTML='<legend>遊び方</legend><div class="play-cards"></div>';group.before(picker);}const cards=picker.querySelector('.play-cards');if(!cards.children.length){for(const [value,label]of [['cooperative','協力'],['competitive','対戦']]){const b=document.createElement('button');b.type='button';b.className='play-choice';b.dataset.playMode=value;b.setAttribute('aria-pressed',String(field.value===value));b.innerHTML='<span class="play-check" aria-hidden="true">'+(field.value===value?'✓':'')+'</span>'+label;b.onclick=()=>{field.value=value;field.dispatchEvent(new Event('change',{bubbles:true}));for(const other of cards.children){const selected=other.dataset.playMode===value;other.setAttribute('aria-pressed',String(selected));other.querySelector('.play-check').textContent=selected?'✓':'';}};cards.append(b);}}for(const b of cards.children){const chosen=field.value===b.dataset.playMode;b.setAttribute('aria-pressed',String(chosen));b.querySelector('.play-check').textContent=chosen?'✓':'';}if(!group.querySelector(':scope > [data-integration-rules-heading]')){const heading=document.createElement('h3');heading.dataset.integrationRulesHeading='';heading.textContent='ルールの調整';group.prepend(heading);}const presetLabel=group.querySelector('label[for="rule-preset"]');if(presetLabel)presetLabel.textContent='解答ルール';group.querySelectorAll(':scope > .rules-summary:not(#whole-rules-description)').forEach(p=>p.remove());const description=$('#whole-rules-description');if(description)$('#rule-options')?.append(description);}
 let transitionPending=false;const previousStartRound=startRound,previousModal=modal;modal=html=>{previousModal(html);patchSettings();};async function settleTransition(action){if(transitionPending)return;FPShared.flushApplause();if(!FPShared.applausePending()){action();return;}transitionPending=true;try{if(await FPShared.settleApplause())action();else toast('拍手の受付を確認できませんでした。状態を確認してもう一度操作してください。');}finally{transitionPending=false;}}startRound=()=>settleTransition(()=>previousStartRound());
 function patchTransitions(){for(const id of ['next','presentation-finalize']){const b=$('#'+id);if(!b||b.integrationTransitionBound)continue;b.integrationTransitionBound=true;const original=b.onclick;b.onclick=e=>settleTransition(()=>original?.call(b,e));}const small=$('.applause-panel > small');if(small&&!(state.finalized||state.result?.finalized)){const last=state.cycle?.pending?.length===1&&state.cycle.pending[0]===state.presenter;small.textContent+=' · '+(last?'確定すると受付終了':'次のお題の開始で受付終了');}}
 function patchHintReading(){const map=window.__fineplayFeedback?.unread,link=$('.history-jump');if(!map||!link)return;const previous=link.onclick,priorLabel=link.getAttribute('aria-label');if([...map.values()].some(v=>v.kind==='hint'))link.setAttribute('aria-label','新着の属性ヒントを表示');link.onclick=e=>{const hint=[...map.entries()].filter(([,v])=>v.kind==='hint'&&state.hints.includes(v.id)).at(-1);if(!hint)return previous?.call(link,e);const chip=[...document.querySelectorAll('.hint-strip .hint-chip')].find(c=>c.dataset.hintLabel===hint[1].id);if(!chip)return previous?.call(link,e);e.preventDefault();chip.scrollIntoView({block:'center',behavior:'instant'});map.delete(hint[0]);chip.classList.remove('hint-unread');chip.querySelector('.hint-new')?.remove();if(priorLabel)link.setAttribute('aria-label',priorLabel);else link.removeAttribute('aria-label');};}
 function patchQuestionVotes(){if(state.rulesSchema!==2)return;for(const b of document.querySelectorAll('[data-presentation-target]')){if(b.dataset.presentationTarget==='problem')continue;const e=state.entries.find(e=>e.id===b.dataset.presentationTarget);if(e&&e.kind!=='question'){if(b.classList.contains('history-quick-fp'))b.remove();else b.closest('.grade-actions')?.remove();}}}
 function patchRuleCopy(){if(state.rulesSchema!==2)return;const wallet=$('#presentation-wallet');if(wallet?.closest('.rights-line'))($('.fp-turn')||$('.fp-scene')||$('.game-column'))?.append(wallet);let line=$('.rights-line');if(!line&&me!==state.presenter&&!state.spectator){line=document.createElement('p');line.className='rights-line';($('.fp-turn')||$('.scene'))?.append(line);}if(line){if(me===state.presenter||state.spectator)line.remove();else{const a=state.allowance,parts=[`次の解答：${a.nextCost===0?'無料':'使えるポイント −'+fmt(a.nextCost)}`];if(a.freeLeft>0)parts.push('無料あと'+a.freeLeft+'回');if(a.grantedFree>0)parts.push('許可された無料'+a.grantedFree+'回');if(a.left!==null)parts.push('解答あと'+a.left+'回');line.textContent=parts.join(' · ');}}const cancellation=$('.pending-cancel small');if(cancellation)cancellation.textContent='取り消しても、使用回数と消費したポイントは戻りません。';if(state.finalized||state.result?.finalized){const next=$('#next');if(next)next.textContent=state.cycle?.status==='complete'?'次の一巡へ →':'次のお題へ →';for(const b of document.querySelectorAll('#undo,[data-note],#undo-confirm,#note-save')){b.disabled=true;b.title='得点確定後は変更できません。';}}const finish=$('#presentation-finalize');if(finish)finish.textContent='確定して結果へ';}
 function paintCommonScores(){const scoreRange=state.rulesSchema===2?200:10,totals=state.lifetimeScoreTotals||state.scoreTotals;if(!totals||state.locked)return;for(const row of document.querySelectorAll('[data-score-player]')){const item=totals.players.find(p=>p.id===row.dataset.scorePlayer),track=row.querySelector('.display-score-track'),bar=track?.querySelector('i');if(!item||!Number.isFinite(item.total)||!bar)continue;const v=Math.max(-scoreRange,Math.min(scoreRange,item.total)),width=Math.abs(v)/scoreRange*50;track.title='共通目盛：0〜±'+scoreRange+'点';bar.style.width=width+'%';bar.style.left=(v<0?50-width:50)+'%';bar.style.right='';bar.classList.toggle('negative',v<0);row.querySelector('.integration-score-overflow')?.remove();if(Math.abs(item.total)>scoreRange){const marker=document.createElement('small');marker.className='integration-score-overflow';marker.title='棒の範囲を超えています。正確な得点は数字で表示。';marker.textContent=item.total<0?'‹':'›';row.append(marker);}}}
 function paintAchievements(){const key=[room,me,state.locked].join(':'),totals=state.achievementTotals;if(key!==achievementKey){achievementKey=key;seeded=false;previousCodes=new Set();pulses.clear();}if(state.locked||!totals)return;const own=totals[me]||{},codes=new Set(Object.keys(knownAchievements).filter(code=>own[code]>0)),now=performance.now();if(seeded&&!document.hidden)for(const code of codes)if(!previousCodes.has(code))pulses.set(code,now);previousCodes=codes;seeded=true;for(const [code,at]of pulses)if(now-at>=850)pulses.delete(code);if(!R.done(state)||!state.finalized)return;const earned=state.players.map(p=>({p,codes:Object.keys(knownAchievements).filter(code=>totals[p.id]?.[code]>0)})).filter(x=>x.codes.length);if(!earned.length)return;const panel=document.createElement('section');panel.id='integration-achievements';panel.className='panel integration-achievements';panel.innerHTML=`<details><summary>実績 <span>${earned.reduce((n,x)=>n+x.codes.length,0)}個</span></summary><div class="integration-achievement-members">${earned.map(({p,codes})=>`<div><b>${esc(p.name)}</b><div class="integration-achievement-badges">${codes.map(code=>{const at=p.id===me?pulses.get(code):undefined;return `<span class="integration-achievement${at===undefined?'':' is-new'}" ${at===undefined?'':`style="--achievement-delay:-${now-at}ms"`}>✦ ${knownAchievements[code]}</span>`;}).join('')}</div></div>`).join('')}</div></details>`;($('.result-stats')||$('.result')||$('.game-column'))?.insertAdjacentElement('afterend',panel);}
 function paintTheme(){const preset=$('#feedback-look')?.value||'fine',p=themes[preset]||themes.fine;document.querySelectorAll('.presentation-star-label').forEach(node=>{node.innerHTML=p.icon+'<span>'+p.label+'</span>';});document.querySelectorAll('[data-presentation-star]').forEach(b=>{b.dataset.look=preset;const star=b.dataset.presentationStar;if(star==='super'){b.querySelector('.hand,.praise-symbol')?.remove();b.insertAdjacentHTML('afterbegin',p.icon);}else if(b.classList.contains('history-quick-fp'))b.innerHTML=p.icon+'<span>'+p.label+'</span>';b.setAttribute('aria-label',star==='super'?'Super '+p.label+' 5つ星':star+'つ星 '+p.label);});document.querySelectorAll('.presentation-fp-mark').forEach(node=>{const count=node.querySelector('b')?.textContent||'';node.innerHTML=p.icon+' '+p.label+' <b>'+esc(count)+'</b>';});const caption=$('.applause-panel h2');if(caption)caption.innerHTML=p.icon+' 出題者に、'+p.label;const applause=$('#applause-tap');if(applause&&me!==state.presenter&&!applause.classList.contains('presentation-climax')){const strong=applause.querySelector('strong');if(strong)strong.textContent=p.label;}}
 function unifyComments(){const button=$('#assist-discussion-new');if(button)button.textContent='＋ コメント';const panel=$('.assist-discussion');if(panel)panel.setAttribute('aria-label','コメント');}
 render=()=>{const x=scrollX,y=scrollY;previousRender();if(state){patchSettings();patchTransitions();patchHintReading();patchQuestionVotes();patchRuleCopy();paintCommonScores();paintAchievements();paintTheme();unifyComments();}scrollTo({left:x,top:y,behavior:'instant'});};
 document.addEventListener('change',event=>{if(event.target?.id==='feedback-look')paintTheme();});
 document.addEventListener('click',event=>{if(event.target?.closest('#assist-discussion-new,[data-assist-stamp]')){const title=$('#modal .assist-dialog h2');if(title)title.textContent='コメント';}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pulses.clear();});
 render();
})();
