/* Final classic-script wrapper. Uses only the role-filtered `state` projection.
 * Reading state and visual effects are device-local; all game actions use send(). */
(()=>{'use strict';
 const oldRender=render,oldBind=bind;
 const motion=matchMedia('(prefers-reduced-motion: reduce)');
 const local={key:'',seen:null,unread:new Map(),read:new Set(),skip:new Set(),effect:null,timer:null,lastCue:-Infinity};
 const metrics={effects:0,merged:0,cues:0,seeds:0};
 const publicNow=s=>!!s&&!s.locked&&!s.hidden&&(s.playMode==='cooperative'||R.done(s));
 const idSelector=id=>`[data-entry="${CSS.escape(id)}"]`;
 const num=n=>Number.isFinite(n)?String(Math.round(n*100)/100):'—';
 const text=e=>e.kind==='question'?R.questionText(e.text):e.text;
 const viewKey=()=>state?[room,state.roundId,me,state.locked].join(':'):'';
 const phaseKey=()=>state?[state.roundId,state.phase].join(':'):'';
 function snapshot(){return {rev:state.rev,public:publicNow(state),done:R.done(state),entries:new Map(state.entries.map(e=>[e.id,{votes:e.votes,stars:e.stars,grade:e.grade}])),comments:new Set(state.comments.map(c=>c.id)),discussion:new Set((state.discussion||[]).map(c=>c.id)),applause:state.applause.total,mine:state.applause.mine,problem:{votes:state.problem.votes,stars:state.problem.stars,grade:state.problem.grade}};}
 function quiet(){clearTimeout(local.timer);local.timer=null;local.effect=null;document.querySelectorAll('.presentation-received').forEach(e=>e.classList.remove('presentation-received'));}
 function queueEffect(kind,id){if(kind==='fine'&&state?.fpRuleVersion==='distinct-donors/1')return;if(document.hidden||motion.matches||local.skip.has(phaseKey()))return;if(local.effect){metrics.merged++;return;}local.effect={kind,id,at:performance.now()};local.timer=setTimeout(()=>{local.timer=null;if(!local.effect||document.hidden)return;metrics.effects++;paintEffect();if(performance.now()-local.lastCue>=1000){local.lastCue=performance.now();metrics.cues++;document.dispatchEvent(new CustomEvent('fineplay:public-feedback',{detail:{kind:local.effect.kind}}));}local.timer=setTimeout(quiet,800);},160);}
 function paintEffect(){if(!local.effect)return;const target=local.effect.kind==='applause'?$('.applause-panel'):local.effect.id==='problem'?$('.problem-fp'):document.querySelector(idSelector(local.effect.id));if(target){target.classList.add('presentation-received');target.style.setProperty('--presentation-delay',`-${Math.max(0,performance.now()-local.effect.at-160)}ms`);}}
 function observe(){const k=viewKey();if(!state||!ready){if(!state)local.seen=null;quiet();return;}if(k!==local.key||!local.seen){local.key=k;local.unread.clear();local.read.clear();quiet();local.seen=snapshot();metrics.seeds++;return;}const prev=local.seen;if(state.rev<=prev.rev)return;const pub=publicNow(state);
  for(const e of state.entries){const before=prev.entries.get(e.id);if(!before){local.unread.set('entry:'+e.id,{entryId:e.id});continue;}if(prev.public&&pub&&((Number.isFinite(e.stars)&&e.stars>before.stars)||(Number.isFinite(e.votes)&&e.votes>before.votes)||e.grade>before.grade))queueEffect('fine',e.id);}
  if(prev.public&&pub&&((Number.isFinite(state.problem.stars)&&state.problem.stars>prev.problem.stars)||(Number.isFinite(state.problem.votes)&&state.problem.votes>prev.problem.votes)||state.problem.grade>prev.problem.grade))queueEffect('fine','problem');
  if(prev.public&&pub&&prev.done&&R.done(state)&&state.applause.total>prev.applause){const own=Math.max(0,state.applause.mine-prev.mine),other=state.applause.total-prev.applause-own;if(other>0)queueEffect('applause','problem');}
  for(const c of state.comments)if(!prev.comments.has(c.id)&&c.author!==me)local.unread.set('comment:'+c.id,{entryId:c.entryId,commentId:c.id});
  for(const c of state.discussion||[])if(!prev.discussion.has(c.id)&&c.author!==me)local.unread.set('discussion:'+c.id,{discussionId:c.id});
  const ids=new Set(state.entries.map(e=>e.id)),comments=new Set(state.comments.map(c=>c.id)),discussion=new Set((state.discussion||[]).map(c=>c.id));for(const [k,v]of local.unread)if(v.entryId&&!ids.has(v.entryId)||v.commentId&&!comments.has(v.commentId)||v.discussionId&&!discussion.has(v.discussionId))local.unread.delete(k);
  local.seen=snapshot();
 }
 function capture(){const list=$('.history-list'),rows=list?[...list.querySelectorAll('[data-entry]')]:[],top=list?.getBoundingClientRect().top||0,anchor=rows.find(e=>e.getBoundingClientRect().bottom>top+2),f=document.activeElement;return {key:local.key,x:scrollX,y:scrollY,scroll:list?.scrollTop||0,anchor:anchor?.dataset.entry,offset:anchor?anchor.getBoundingClientRect().top-top:0,end:list?list.scrollHeight-list.scrollTop-list.clientHeight<40:true,open:rows.filter(e=>e.open).map(e=>e.dataset.entry),focus:{id:f?.id,entry:f?.closest('[data-entry]')?.dataset.entry,grade:f?.dataset.grade,star:f?.dataset.presentationStar,quick:f?.classList.contains('history-quick-fp'),target:f?.dataset.presentationTarget,comment:f?.dataset.comment,note:f?.dataset.note,combo:f?.dataset.displayCombo,summary:f?.tagName==='SUMMARY',selection:f?.selectionStart!==undefined?[f.selectionStart,f.selectionEnd,f.selectionDirection]:null}};}
 function restore(saved){if(saved.key!==local.key)return;const list=$('.history-list');for(const id of saved.open)document.querySelector(idSelector(id))?.setAttribute('open','');if(list){const anchor=saved.anchor?list.querySelector(idSelector(saved.anchor)):null;if(anchor)list.scrollTop+=anchor.getBoundingClientRect().top-list.getBoundingClientRect().top-saved.offset;else list.scrollTop=saved.scroll;}const f=saved.focus;let next=f.id?document.getElementById(f.id):null;const row=f.entry?document.querySelector(idSelector(f.entry)):null;if(!next&&f.star&&row)next=f.quick?row.querySelector('.history-quick-fp'):row.querySelector(`.presentation-stars [data-presentation-star="${f.star}"]`);if(!next&&f.star)next=document.querySelector(`[data-presentation-target="${CSS.escape(f.target)}"][data-presentation-star="${f.star}"]`);if(!next&&row){if(f.summary)next=row.querySelector('summary');else if(f.grade)next=row.querySelector(`[data-grade="${f.grade}"]`);else if(f.comment)next=row.querySelector('[data-comment]');else if(f.note)next=row.querySelector('[data-note]');else if(f.combo)next=row.querySelector('[data-display-combo]');}next?.focus({preventScroll:true});if(next&&f.selection)try{next.setSelectionRange(...f.selection);}catch{}scrollTo(saved.x,saved.y);}
 function markVisible(){const list=$('.history-list');if(!list)return;const rect=list.getBoundingClientRect();if(rect.bottom<0||rect.top>innerHeight)return;const top=Math.max(0,rect.top),bottom=Math.min(innerHeight,rect.bottom);for(const row of list.querySelectorAll('[data-entry]')){const r=row.getBoundingClientRect();if(r.top<bottom&&r.bottom>top){local.read.add(row.dataset.entry);for(const [k,v]of local.unread)if(v.entryId===row.dataset.entry){if(v.commentId){const c=document.querySelector(`[data-comment-id="${CSS.escape(v.commentId)}"]`),cr=c?.getBoundingClientRect();if(!cr||cr.top>=bottom||cr.bottom<=top)continue;}local.unread.delete(k);}}}paintUnread();}
 function paintUnread(){const history=$('#history');if(!history)return;const b=$('#presentation-unread');if(b){b.hidden=!local.unread.size;b.textContent=`未読 ${local.unread.size}件`;}history.querySelectorAll('[data-entry]').forEach(e=>e.classList.toggle('presentation-unread',[...local.unread.values()].some(v=>v.entryId===e.dataset.entry)));const link=$('.history-jump');if(link){link.querySelectorAll('.unread-badge').forEach(e=>e.remove());link.classList.toggle('has-unread',local.unread.size>0);link.setAttribute('aria-label',local.unread.size?`質問履歴・未読 ${local.unread.size}件`:'質問履歴');}}
 function jump(id,commentId){filter='all';search='';render();const row=document.querySelector(idSelector(id));if(!row)return;row.open=true;const target=commentId?document.querySelector(`[data-comment-id="${CSS.escape(commentId)}"]`)||row:row;const scroller=document.querySelector('#history .history-list');if(scroller)scroller.scrollTop+=target.getBoundingClientRect().top-scroller.getBoundingClientRect().top-scroller.clientHeight/2+target.getBoundingClientRect().height/2;row.querySelector('summary')?.focus({preventScroll:true});markVisible();window.dispatchEvent(new Event('fineplay:history-follow'));}
 function paintHistory(){const card=$('.fp-card'),cardEntry=state.entries.find(e=>e.id===card?.dataset.cardEntry);if(cardEntry?.answerLabel&&card.querySelector('.answer-chip'))card.querySelector('.answer-chip').textContent=cardEntry.answerLabel;const history=$('#history'),grid=$('.play-grid');if(!history||!grid||state.locked)return;grid.append(history);history.classList.add('presentation-history');history.classList.toggle('presentation-long',state.entries.length>4);const head=history.querySelector('.section-head');if(head&&!$('#presentation-history-nav'))head.insertAdjacentHTML('afterend','<div id="presentation-history-nav" class="presentation-history-nav"><a href="#presentation-current" id="presentation-current-link">今の質問へ ↑</a><div><button id="presentation-unread" class="quiet" hidden></button><button id="presentation-newest" class="quiet">最新へ ↓</button></div></div>');
  const cs=new Map();for(const c of state.comments){if(!cs.has(c.entryId))cs.set(c.entryId,[]);cs.get(c.entryId).push(c);}for(const row of history.querySelectorAll('[data-entry]')){const e=state.entries.find(x=>x.id===row.dataset.entry);if(!e)continue;const popular=!state.hidden&&(e.stars>0||e.votes>0||e.grade>0);row.classList.toggle('presentation-popular',popular);const main=row.querySelector('.clue-main');main?.querySelectorAll('.presentation-fp-mark').forEach(e=>e.remove());if(main?.querySelector('small'))main.querySelector('small').textContent=person(e.asker);main?.insertAdjacentHTML('beforeend',`<span class="presentation-fp-mark" ${popular?'':'style="visibility:hidden" aria-hidden="true"'}>${HAND} FinePlay <b>${popular?num(e.stars??e.votes):''}</b></span>`);row.querySelectorAll('.clue-comment').forEach(c=>c.remove());const comments=cs.get(e.id)||[];if(comments.length)row.insertAdjacentHTML('afterend',`<section class="presentation-thread" data-thread-entry="${esc(e.id)}" aria-label="Q${e.n}のコメント">${comments.map(c=>`<article data-comment-id="${esc(c.id)}"><small>${esc(person(c.author))}</small><p>${esc(c.text)}</p></article>`).join('')}</section>`);const label=e.answerLabel||R.labels[e.answer];if(label)row.querySelector('.answer-chip').textContent=label;row.querySelector('summary')?.setAttribute('title','評価・コメントの操作を開く');}
  document.querySelectorAll('.comment-panel').forEach(panel=>{const combos=panel.querySelector('#combo-new');if(combos)history.append(combos);panel.querySelectorAll('.fp-discussion,.assist-discussion,[data-discussion-panel]').forEach(e=>history.append(e));panel.remove();});
  document.querySelectorAll('.assist-discussion-comment').forEach((e,i)=>{const c=state.discussion?.[i];if(c)e.dataset.discussionId=c.id;});const list=history.querySelector('.history-list');list?.addEventListener('scroll',markVisible,{passive:true});on('presentation-newest',()=>{const id=state.entries.at(-1)?.id;if(id)jump(id);});on('presentation-unread',()=>{const v=[...local.unread.values()][0];if(v?.entryId)jump(v.entryId,v.commentId);else if(v?.discussionId){document.querySelector(`[data-discussion-id="${CSS.escape(v.discussionId)}"]`)?.scrollIntoView({block:'center',behavior:'instant'});for(const [k,n]of local.unread)if(n.discussionId===v.discussionId)local.unread.delete(k);paintUnread();}});const link=$('.history-jump');if(link)link.onclick=e=>{e.preventDefault();const v=[...local.unread.values()].find(v=>v.entryId);if(v)jump(v.entryId,v.commentId);else history.scrollIntoView({block:'start',behavior:'instant'});};paintUnread();
 }
 function stars(){if(state.rulesSchema!==2||state.locked)return;document.querySelectorAll('.history-quick-fp').forEach(b=>b.remove());document.querySelectorAll('.grade-actions').forEach(group=>{const old=group.querySelector('[data-target]');if(!old)return;const target=old.dataset.target,e=target==='problem'?state.problem:state.entries.find(e=>e.id===target);if(!e)return;const self=target==='problem'?me===state.presenter:e.asker===me,disabled=self||!ready||busy;group.classList.add('presentation-stars');group.innerHTML=`<span class="presentation-star-label">${HAND}<span>FinePlay</span></span>${[1,2,3].map(n=>`<button type="button" data-presentation-target="${esc(target)}" data-presentation-star="${n}" class="vote ${!e.mySuper&&e.myStars===n?'voted':''}" aria-label="${n}つ星 FinePlay" aria-pressed="${!e.mySuper&&e.myStars===n}" ${disabled?'disabled':''}>${'★'.repeat(n)}</button>`).join('')}<button type="button" data-presentation-target="${esc(target)}" data-presentation-star="super" class="vote super ${e.mySuper?'voted':''}" aria-label="Super FinePlay 5つ星" aria-pressed="${!!e.mySuper}" ${disabled?'disabled':''}>${HAND}<span>Super <small>5★</small></span></button>`;group.querySelectorAll('[data-presentation-star]').forEach(b=>b.onclick=()=>{const isSuper=b.dataset.presentationStar==='super',n=isSuper?0:Number(b.dataset.presentationStar),remove=isSuper?e.mySuper:!e.mySuper&&e.myStars===n;send(target==='problem'?'voteProblem':'vote',{...(target==='problem'?{}:{entryId:target}),stars:remove?0:n,super:remove?false:isSuper});});});}
 function quickFineplay(){if(state.rulesSchema!==2||state.locked||state.finalized||state.result?.finalized||state.playMode!=='cooperative')return;for(const row of document.querySelectorAll('#history [data-entry]')){const e=state.entries.find(e=>e.id===row.dataset.entry);if(!e||e.asker===me)continue;const summary=row.querySelector('summary');if(!summary)continue;summary.insertAdjacentHTML('beforeend',`<button type="button" class="vote history-quick-fp ${!e.mySuper&&e.myStars===1?'voted':''}" data-presentation-target="${esc(e.id)}" data-presentation-star="1" aria-label="Q${e.n}に1つ星 FinePlay" aria-pressed="${!e.mySuper&&e.myStars===1}" ${!ready||busy?'disabled':''}>${HAND}<span>FinePlay</span></button>`);summary.querySelector('.history-quick-fp').onclick=event=>{event.preventDefault();event.stopPropagation();send('vote',{entryId:e.id,stars:!e.mySuper&&e.myStars===1?0:1,super:false});};}}
 function paintApplause(updateCopy=true){const b=$('#applause-tap');if(!b)return;const finalized=!!(state.finalized||state.result?.finalized),mine=me===state.presenter?null:finalized?state.applause.mine:Math.min(100,Math.max(state.applause.mine,Number($('#tap-count')?.textContent.split('/')[0])||0)),level=mine===null?0:mine/100;if(finalized&&mine!==null&&$('#tap-count'))$('#tap-count').textContent=mine+' / 100';b.style.setProperty('--applause-power',String(level));b.classList.toggle('presentation-climax',mine===100);b.setAttribute('aria-label',mine===null?'みんなからの拍手':mine===100?'100回の拍手を送りました':`出題者に拍手 ${mine}/100`);b.querySelector('strong').textContent=mine===null?'みんなの拍手':mine===100?'100 / 100 ありがとう！':'FinePlay!';if(updateCopy){const caption=$('.applause-panel h2');if(caption)caption.innerHTML=HAND+' このお題に、拍手';const total=$('.applause-total');if(total)total.innerHTML=`拍手 <b>${num(state.applause.total)}</b>回 <span>· 出題者の得点 <b>＋${num(state.applause.points)}</b></span>`;const small=$('.applause-panel > small');if(small)small.textContent=state.rulesSchema===2?`1人100回まで · 1回＋${num(state.rules.applausePoints)}点`:'1人100回まで · 100回で＋1点';}if(mine!==null&&!b.presentationBound){b.presentationBound=true;const previousClick=b.onclick;b.onclick=event=>{previousClick?.call(b,event);paintApplause(false);};}}
 function paintStage(){const current=$('.fp-card')||$('.scene')||$('.result');if(current)current.id='presentation-current';if(!R.done(state)||state.locked)return;const result=$('.result');if(!result)return;result.classList.add('presentation-result');const skipped=local.skip.has(phaseKey());result.classList.toggle('presentation-skipped',skipped);result.setAttribute('aria-label','このお題の答え合わせ');result.querySelector('.eyebrow').textContent=state.phase==='solved'?'SOLVED · お見事！':'ANSWER · 答え合わせ';if(!$('#presentation-stage-nav'))result.insertAdjacentHTML('afterbegin',`<nav id="presentation-stage-nav" class="presentation-stage-nav" aria-label="お題の進行"><span class="is-current">答え合わせ</span><span>拍手・感想</span><span>次のお題</span><button id="presentation-skip" class="quiet" ${skipped?'disabled':''}>${skipped?'演出をスキップ済み':'演出をスキップ'}</button></nav>`);on('presentation-skip',()=>{local.skip.add(phaseKey());quiet();render();});const next=$('#next');if(next){let footer=$('#presentation-result-next');if(!footer){footer=document.createElement('div');footer.id='presentation-result-next';footer.className='presentation-result-next';$('.game-column')?.append(footer);}footer.append(next);next.textContent='拍手を締めて、次へ →';}result.querySelector('.answer-reveal')?.setAttribute('aria-label','公開された答え');result.querySelectorAll(':scope > .small').forEach(e=>e.remove());}
 function paintTotals(){if(state.locked)return;const dock=$('#display-scores'),column=$('.game-column');if(dock&&column)column.prepend(dock);const totals=state.lifetimeScoreTotals||state.scoreTotals;if(totals){const title=$('.display-score-title');if(title)title.textContent=['confirmed','finalized'].includes(totals.scope)?'確定通算得点':state.lifetimeScoreTotals?'通算得点':'得点';for(const row of document.querySelectorAll('[data-score-player]')){const item=totals.players.find(p=>p.id===row.dataset.scorePlayer);if(!item)continue;row.querySelector('.display-score-overflow')?.remove();const b=row.querySelector('b');if(b)b.innerHTML=num(item.total)+'<small>点</small>';const bar=row.querySelector('.display-score-track i');if(bar){const v=Math.max(-10,Math.min(10,item.total));bar.classList.toggle('negative',v<0);bar.style.left=(v<0?50+v*5:50)+'%';bar.style.width=Math.abs(v)*5+'%';}}}const wallet=state.wallet;if(wallet&&Number.isFinite(wallet.balance)){let box=$('#presentation-wallet');if(!box){box=document.createElement('div');box.id='presentation-wallet';box.className='presentation-wallet';($('.rights-line')||$('.fp-turn')||$('.game-column'))?.append(box);}box.innerHTML=`<span>使えるポイント</span><b>${num(wallet.balance)}</b><small>得点とは別</small>`;}}
 const awardLabels={fineplayReceived:'FinePlay賞',applauseReceived:'拍手賞',questions:'質問賞',correct:'正解賞',combos:'Combo賞'};
 function paintCycle(){if(state.locked||!state.cycle)return;const c=state.cycle,done=R.done(state),finalized=!!(state.finalized||state.result?.finalized);
  if(done&&c.status==='active'&&c.pending.length===1&&c.pending[0]===state.presenter){const footer=$('#presentation-result-next')||$('.game-column');if(footer&&state.canFinalize){const pendingOwn=me!==state.presenter&&Number($('#tap-count')?.textContent.split('/')[0])>state.applause.mine;footer.insertAdjacentHTML('afterbegin',`<button id="presentation-finalize" class="primary" ${!ready||busy||pendingOwn?'disabled':''}>拍手を締めて、表彰へ ✦</button>`);on('presentation-finalize',()=>send('finalize'));const next=$('#next');if(next)next.hidden=true;}}
  if(finalized){const b=$('#applause-tap');if(b){b.disabled=true;b.onclick=null;b.setAttribute('aria-label','拍手受付は終了しました');}const small=$('.applause-panel > small');if(small)small.textContent='このお題の拍手は確定しました';document.querySelectorAll('[data-presentation-star],[data-grade]').forEach(b=>b.disabled=true);}
  const r=state.cycleResult;if(!r?.finalized)return;const active=r.id===c.id&&c.status==='complete',parent=$('.play-grid');if(!parent)return;const podium=r.podium.filter(p=>p.rank<=3),names=ids=>ids.map(id=>r.podium.find(p=>p.playerId===id)?.name||person(id)).map(esc).join('・');
  const categories=r.podium.map(p=>{const t=r.totals[p.playerId];return `<tr><th scope="row">${esc(p.name)}</th><td>${num(p.score)}</td><td>${num(t?.fineplayReceived?.count)}票 / ${num(t?.fineplayReceived?.stars)}★</td><td>${num(t?.applauseReceived?.count)}回</td></tr>`;}).join('');
  const awards=r.awards.map(a=>`<article class="presentation-award"><span>${a.code==='fineplayReceived'?HAND:'<span aria-hidden="true">✦</span>'}</span><h3>${esc(awardLabels[a.code]||a.code)}</h3><b>${names(a.playerIds)}</b><small>${num(a.value)}${a.metric==='stars'?'★':a.code==='applauseReceived'?'回':'件'}${a.playerIds.length>1?' · 同率':''}</small></article>`).join('');
  parent.insertAdjacentHTML('beforeend',`<section id="presentation-cycle" class="panel presentation-cycle" aria-label="一巡の確定結果"><${active?'div':'details'} ${active?'':'class="presentation-cycle-archive"'}>${active?'':`<summary>前の一巡の確定結果</summary>`}<div class="presentation-cycle-head"><div><span class="eyebrow">EVERYONE HAD THEIR TURN</span><h2>一巡、おつかれさま！</h2></div><span>全${r.roundIds.length}題 · 確定</span></div><div class="presentation-podium" aria-label="通算得点順位">${podium.map(p=>`<article class="presentation-podium-place place-${p.rank}"><small>${p.rank}位${r.podium.filter(x=>x.rank===p.rank).length>1?' · 同率':''}</small><h3>${esc(p.name)}</h3><b>${num(p.score)}<small>点</small></b></article>`).join('')}</div><div class="presentation-awards">${awards||'<p class="small">今回は該当する部門賞がありません。</p>'}</div>${['fineplayReceived','applauseReceived'].filter(code=>!r.awards.some(a=>a.code===code)).map(code=>`<p class="small">${awardLabels[code]}：今回は該当なし</p>`).join('')}<details class="presentation-cycle-totals"><summary>全員の確定合計</summary><div class="stats-scroll"><table><thead><tr><th>メンバー</th><th>得点</th><th>受けたFinePlay</th><th>受けた拍手</th></tr></thead><tbody>${categories}</tbody></table></div></details>${r.skipped.length?`<p class="small">出題を見送った人：${names(r.skipped.map(x=>x.playerId))}</p>`:''}<small>部門賞はこの一巡の確定記録から集計</small></${active?'div':'details'}></section>`);
  if(active){const heading=$('#presentation-stage-nav');heading?.querySelectorAll('span').forEach((e,i)=>{e.classList.toggle('is-current',i===2);if(i===2)e.textContent='一巡の表彰';});}
 }
 function paintProblemStats(){if(state.rulesSchema!==2||!state.result||state.locked)return;const panel=$('.result-stats');if(!panel)return;const r=R.resolveSnapshot(state,state.result),c=r.counts;panel.innerHTML=`<div class="section-head"><h2>このお題の記録</h2><span class="small">${r.finalized?'確定':'拍手受付中'}</span></div><p class="small">質問 ${num(c.questions)} · 解答 ${num(c.guesses)}</p><div class="stats-scroll"><table><thead><tr><th>メンバー</th><th>質問 / 解答</th><th>受けたFinePlay</th><th>受けた拍手</th><th>得点</th></tr></thead><tbody>${r.players.filter(p=>!p.spectator).map(p=>`<tr><th scope="row">${esc(p.name)}${p.presenter?' <small>出題</small>':''}</th><td>${num(p.questions)} / ${num(p.guesses)}</td><td>${num(p.fineplayReceived.count)}票 / ${num(p.fineplayReceived.stars)}★</td><td>${num(p.applauseReceived.count)}回</td><td><b>${num(p.score)}</b></td></tr>`).join('')}</tbody></table></div>`;}
 function paint(){document.body.classList.toggle('presentation-active',!!state&&state.phase!=='lobby');if(!state)return;paintHistory();stars();quickFineplay();paintApplause();paintStage();paintTotals();paintCycle();paintProblemStats();paintEffect();}
 bind=()=>{oldBind();};
 render=()=>{const saved=capture();observe();oldRender();paint();restore(saved);};
 document.addEventListener('visibilitychange',()=>{quiet();local.seen=null;});motion.addEventListener('change',quiet);window.addEventListener('scroll',markVisible,{passive:true});
 window.FPPresentation={metrics,refresh:render,reset:()=>{local.seen=null;quiet();},publicNow};
 render();
})();
