const assert=require('node:assert/strict'),R=require('./engine.js');let id=0,checks=0,s;
const act=(who,type,extra={})=>s=R.apply(s,who,{id:'stage-test-'+(++id),roundId:s.roundId,scope:'test',type,...extra});
const deny=(who,type,extra={})=>assert.throws(()=>R.apply(s,who,{id:'stage-test-'+(++id),roundId:s.roundId,scope:'test',type,...extra}));
function setup(rules={preset:'dead'},mode='live'){s=R.create('h','Host');s=R.join(s,'a','Alice');s=R.join(s,'b','Bob');act('h','start',{presenter:'h',mode,scope:'test',secretAnswer:'Answer',rules});}
function guess(who='a',answer='incorrect'){act(who,'ask',{kind:'guess',text:'Answer'});act('h','answer',{pendingId:s.pending.id,answer});}
function test(name,f){f();checks++;console.log('PASS',name);}
test('new dead default has no hard cap and three free guesses',()=>{setup();assert.equal(s.rules.costModel,'staged');assert.equal(s.rules.limit,'none');for(let i=1;i<=3;i++){assert.equal(R.view(s,'a').allowance.nextCost,0);guess();assert.equal(R.summary(s).players[1].score,0);assert.equal(R.view(s,'a').allowance.freeLeft,3-i);}assert.equal(R.view(s,'a').allowance.nextCost,1);});
test('fourth through sixth cost one, seventh onward two with cumulative deductions',()=>{for(const [i,total,next] of [[4,1,1],[5,2,1],[6,3,2],[7,5,2],[8,7,2],[9,9,2]]){guess();const v=R.view(s,'a');assert.equal(v.allowance.used,i);assert.equal(v.myStats.guessPenalty,total);assert.equal(v.myStats.score,-total);assert.equal(v.allowance.nextCost,next);assert.equal(v.allowance.canGuess,true);}});
test('free allocation is per person and resets on next round',()=>{assert.equal(R.view(s,'b').allowance.nextCost,0);assert.equal(R.view(s,'b').allowance.freeLeft,3);act('h','reveal',{text:'Answer'});act('h','start',{presenter:'h',mode:'live',rules:{preset:'dead'},secretAnswer:'Answer'});assert.equal(R.view(s,'a').allowance.used,0);assert.equal(R.view(s,'a').allowance.freeLeft,3);});
test('correct bonus remains three: third yields three, fourth two, sixth zero, seventh minus two',()=>{for(const [attempt,score] of [[3,3],[4,2],[6,0],[7,-2]]){setup();for(let i=1;i<=attempt;i++)guess('a',i===attempt?'correct':'incorrect');assert.equal(R.summary(s).players[1].score,score);}});
test('cancellation consumes its ordinal, undo never double charges a paid guess',()=>{setup();for(let i=0;i<3;i++)guess();act('a','ask',{kind:'guess',text:'cancel'});act('a','cancel',{pendingId:s.pending.id});assert.equal(R.view(s,'a').myStats.guessPenalty,1);guess();assert.equal(R.view(s,'a').myStats.guessPenalty,2);act('h','undo');act('h','answer',{pendingId:s.pending.id,answer:'incorrect'});assert.equal(R.view(s,'a').allowance.used,5);assert.equal(R.view(s,'a').myStats.guessPenalty,2);});
test('zero-budget points mode allows free three then requires earned points',()=>{setup({preset:'dead',limit:'points',initialPoints:0});for(let i=0;i<3;i++)guess();deny('a','ask',{kind:'guess',text:'unfunded'});act('a','ask',{kind:'question',text:'Useful question'});act('h','answer',{pendingId:s.pending.id,answer:'yes'});act('h','vote',{entryId:s.entries.at(-1).id,grade:1});assert.equal(R.view(s,'a').allowance.balance,1);guess();assert.equal(R.view(s,'a').allowance.balance,0);});
test('points mode reserves enough for the next tier and keeps questions open',()=>{setup({preset:'dead',limit:'points',initialPoints:3});for(let i=0;i<6;i++)guess();assert.equal(R.view(s,'a').allowance.nextCost,2);assert.equal(R.view(s,'a').allowance.canGuess,false);act('a','ask',{kind:'question',text:'Recover'});act('h','answer',{pendingId:s.pending.id,answer:'yes'});act('h','vote',{entryId:s.entries.at(-1).id,grade:2});assert.equal(R.view(s,'a').allowance.canGuess,true);guess();assert.equal(R.view(s,'a').allowance.balance,0);});
test('explicit count cap still works and does not silently switch to unlimited',()=>{setup({preset:'dead',limit:'count',attempts:3});for(let i=0;i<3;i++)guess();assert.equal(R.view(s,'a').allowance.left,0);deny('a','ask',{kind:'guess',text:'Fourth'});});
test('flat option and existing saved rounds retain their original costs',()=>{setup({preset:'dead',costModel:'flat'});guess();assert.equal(R.view(s,'a').myStats.score,-1);delete s.rules.costModel;guess();assert.equal(R.view(s,'a').myStats.score,-2);assert.equal(R.view(s,'a').allowance.nextCost,1);});
test('custom base cost scales paid stages but never the free stage',()=>{setup({preset:'dead',guessCost:2});for(let i=1;i<=7;i++)guess();assert.equal(R.view(s,'a').myStats.guessPenalty,10);assert.equal(R.view(s,'a').allowance.nextCost,4);});
test('casual remains free beyond the staged thresholds',()=>{setup({preset:'casual'});for(let i=0;i<10;i++)guess();assert.equal(R.view(s,'a').myStats.guessPenalty,0);assert.equal(R.view(s,'a').allowance.nextCost,0);assert.equal(R.view(s,'a').allowance.canGuess,true);});
test('sealed points mode stays forbidden and unknown cost models reject',()=>{setup();act('h','reveal',{text:'Answer'});deny('h','start',{presenter:'h',mode:'sealed',rules:{preset:'dead',limit:'points'}});deny('h','start',{presenter:'h',mode:'live',rules:{preset:'dead',costModel:'unknown'}});});
console.log(`RESULT ${checks}/${checks}`);
